insert into items values (1, 'Master Ball');
insert into items values (2, 'Ultra Ball');
insert into items values (3, 'Great Ball');
insert into items values (4, 'Poké Ball');
insert into items values (5, 'Safari Ball');
insert into items values (6, 'Net Ball');
insert into items values (7, 'Dive Ball');
insert into items values (8, 'Nest Ball');
insert into items values (9, 'Repeat Ball');
insert into items values (10, 'Timer Ball');
insert into items values (11, 'Luxury Ball');
insert into items values (12, 'Premier Ball');
insert into items values (13, 'Dusk Ball');
insert into items values (14, 'Heal Ball');
insert into items values (15, 'Quick Ball');
insert into items values (16, 'Cherish Ball');
insert into items values (17, 'Potion');
insert into items values (18, 'Antidote');
insert into items values (19, 'Burn Heal');
insert into items values (20, 'Ice Heal');
insert into items values (21, 'Awakening');
insert into items values (22, 'Paralyze Heal');
insert into items values (23, 'Full Restore');
insert into items values (24, 'Max Potion');
insert into items values (25, 'Hyper Potion');
insert into items values (26, 'Super Potion');
insert into items values (27, 'Full Heal');
insert into items values (28, 'Revive');
insert into items values (29, 'Max Revive');
insert into items values (30, 'Fresh Water');
insert into items values (31, 'Soda Pop');
insert into items values (32, 'Lemonade');
insert into items values (33, 'Moomoo Milk');
insert into items values (34, 'Energy Powder');
insert into items values (35, 'Energy Root');
insert into items values (36, 'Heal Powder');
insert into items values (37, 'Revival Herb');
insert into items values (38, 'Ether');
insert into items values (39, 'Max Ether');
insert into items values (40, 'Elixir');
insert into items values (41, 'Max Elixir');
insert into items values (42, 'Lava Cookie');
insert into items values (43, 'Berry Juice');
insert into items values (44, 'Sacred Ash');
insert into items values (45, 'HP Up');
insert into items values (46, 'Protein');
insert into items values (47, 'Iron');
insert into items values (48, 'Carbos');
insert into items values (49, 'Calcium');
insert into items values (50, 'Rare Candy');
insert into items values (51, 'PP Up');
insert into items values (52, 'Zinc');
insert into items values (53, 'PP Max');
insert into items values (54, 'Old Gateau');
insert into items values (55, 'Guard Spec.');
insert into items values (56, 'Dire Hit');
insert into items values (57, 'X Attack');
insert into items values (58, 'X Defense');
insert into items values (59, 'X Speed');
insert into items values (60, 'X Accuracy');
insert into items values (61, 'X Sp. Atk');
insert into items values (62, 'X Sp. Def');
insert into items values (63, 'Poké Doll');
insert into items values (64, 'Fluffy Tail');
insert into items values (65, 'Blue Flute');
insert into items values (66, 'Yellow Flute');
insert into items values (67, 'Red Flute');
insert into items values (68, 'Black Flute');
insert into items values (69, 'White Flute');
insert into items values (70, 'Shoal Salt');
insert into items values (71, 'Shoal Shell');
insert into items values (72, 'Red Shard');
insert into items values (73, 'Blue Shard');
insert into items values (74, 'Yellow Shard');
insert into items values (75, 'Green Shard');
insert into items values (76, 'Super Repel');
insert into items values (77, 'Max Repel');
insert into items values (78, 'Escape Rope');
insert into items values (79, 'Repel');
insert into items values (80, 'Sun Stone');
insert into items values (81, 'Moon Stone');
insert into items values (82, 'Fire Stone');
insert into items values (83, 'Thunder Stone');
insert into items values (84, 'Water Stone');
insert into items values (85, 'Leaf Stone');
insert into items values (86, 'Tiny Mushroom');
insert into items values (87, 'Big Mushroom');
insert into items values (88, 'Pearl');
insert into items values (89, 'Big Pearl');
insert into items values (90, 'Stardust');
insert into items values (91, 'Star Piece');
insert into items values (92, 'Nugget');
insert into items values (93, 'Heart Scale');
insert into items values (94, 'Honey');
insert into items values (95, 'Growth Mulch');
insert into items values (96, 'Damp Mulch');
insert into items values (97, 'Stable Mulch');
insert into items values (98, 'Gooey Mulch');
insert into items values (99, 'Root Fossil');
insert into items values (100, 'Claw Fossil');
insert into items values (101, 'Helix Fossil');
insert into items values (102, 'Dome Fossil');
insert into items values (103, 'Old Amber');
insert into items values (104, 'Armor Fossil');
insert into items values (105, 'Skull Fossil');
insert into items values (106, 'Rare Bone');
insert into items values (107, 'Shiny Stone');
insert into items values (108, 'Dusk Stone');
insert into items values (109, 'Dawn Stone');
insert into items values (110, 'Oval Stone');
insert into items values (111, 'Odd Keystone');
insert into items values (112, 'Griseous Orb');
insert into items values (113, 'Tea');
insert into items values (114, 'Unknown');
insert into items values (115, 'Autograph');
insert into items values (116, 'Douse Drive');
insert into items values (117, 'Shock Drive');
insert into items values (118, 'Burn Drive');
insert into items values (119, 'Chill Drive');
insert into items values (120, 'Unknown');
insert into items values (121, 'Pokémon Box');
insert into items values (122, 'Medicine Pocket');
insert into items values (123, 'TM Case');
insert into items values (124, 'Candy Jar');
insert into items values (125, 'Power-Up Pocket');
insert into items values (126, 'Clothing Trunk');
insert into items values (127, 'Catching Pocket');
insert into items values (128, 'Battle Pocket');
insert into items values (129, 'Unknown');
insert into items values (130, 'Unknown');
insert into items values (131, 'Unknown');
insert into items values (132, 'Unknown');
insert into items values (133, 'Unknown');
insert into items values (134, 'Sweet Heart');
insert into items values (135, 'Adamant Orb');
insert into items values (136, 'Lustrous Orb');
insert into items values (137, 'Greet Mail');
insert into items values (138, 'Favored Mail');
insert into items values (139, 'RSVP Mail');
insert into items values (140, 'Thanks Mail');
insert into items values (141, 'Inquiry Mail');
insert into items values (142, 'Like Mail');
insert into items values (143, 'Reply Mail');
insert into items values (144, 'Bridge Mail S');
insert into items values (145, 'Bridge Mail D');
insert into items values (146, 'Bridge Mail T');
insert into items values (147, 'Bridge Mail V');
insert into items values (148, 'Bridge Mail M');
insert into items values (149, 'Cheri Berry');
insert into items values (150, 'Chesto Berry');
insert into items values (151, 'Pecha Berry');
insert into items values (152, 'Rawst Berry');
insert into items values (153, 'Aspear Berry');
insert into items values (154, 'Leppa Berry');
insert into items values (155, 'Oran Berry');
insert into items values (156, 'Persim Berry');
insert into items values (157, 'Lum Berry');
insert into items values (158, 'Sitrus Berry');
insert into items values (159, 'Figy Berry');
insert into items values (160, 'Wiki Berry');
insert into items values (161, 'Mago Berry');
insert into items values (162, 'Aguav Berry');
insert into items values (163, 'Iapapa Berry');
insert into items values (164, 'Razz Berry');
insert into items values (165, 'Bluk Berry');
insert into items values (166, 'Nanab Berry');
insert into items values (167, 'Wepear Berry');
insert into items values (168, 'Pinap Berry');
insert into items values (169, 'Pomeg Berry');
insert into items values (170, 'Kelpsy Berry');
insert into items values (171, 'Qualot Berry');
insert into items values (172, 'Hondew Berry');
insert into items values (173, 'Grepa Berry');
insert into items values (174, 'Tamato Berry');
insert into items values (175, 'Cornn Berry');
insert into items values (176, 'Magost Berry');
insert into items values (177, 'Rabuta Berry');
insert into items values (178, 'Nomel Berry');
insert into items values (179, 'Spelon Berry');
insert into items values (180, 'Pamtre Berry');
insert into items values (181, 'Watmel Berry');
insert into items values (182, 'Durin Berry');
insert into items values (183, 'Belue Berry');
insert into items values (184, 'Occa Berry');
insert into items values (185, 'Passho Berry');
insert into items values (186, 'Wacan Berry');
insert into items values (187, 'Rindo Berry');
insert into items values (188, 'Yache Berry');
insert into items values (189, 'Chople Berry');
insert into items values (190, 'Kebia Berry');
insert into items values (191, 'Shuca Berry');
insert into items values (192, 'Coba Berry');
insert into items values (193, 'Payapa Berry');
insert into items values (194, 'Tanga Berry');
insert into items values (195, 'Charti Berry');
insert into items values (196, 'Kasib Berry');
insert into items values (197, 'Haban Berry');
insert into items values (198, 'Colbur Berry');
insert into items values (199, 'Babiri Berry');
insert into items values (200, 'Chilan Berry');
insert into items values (201, 'Liechi Berry');
insert into items values (202, 'Ganlon Berry');
insert into items values (203, 'Salac Berry');
insert into items values (204, 'Petaya Berry');
insert into items values (205, 'Apicot Berry');
insert into items values (206, 'Lansat Berry');
insert into items values (207, 'Starf Berry');
insert into items values (208, 'Enigma Berry');
insert into items values (209, 'Micle Berry');
insert into items values (210, 'Custap Berry');
insert into items values (211, 'Jaboca Berry');
insert into items values (212, 'Rowap Berry');
insert into items values (213, 'Bright Powder');
insert into items values (214, 'White Herb');
insert into items values (215, 'Macho Brace');
insert into items values (216, 'Exp. Share');
insert into items values (217, 'Quick Claw');
insert into items values (218, 'Soothe Bell');
insert into items values (219, 'Mental Herb');
insert into items values (220, 'Choice Band');
insert into items values (221, 'King''s Rock');
insert into items values (222, 'Silver Powder');
insert into items values (223, 'Amulet Coin');
insert into items values (224, 'Cleanse Tag');
insert into items values (225, 'Soul Dew');
insert into items values (226, 'Deep Sea Tooth');
insert into items values (227, 'Deep Sea Scale');
insert into items values (228, 'Smoke Ball');
insert into items values (229, 'Everstone');
insert into items values (230, 'Focus Band');
insert into items values (231, 'Lucky Egg');
insert into items values (232, 'Scope Lens');
insert into items values (233, 'Metal Coat');
insert into items values (234, 'Leftovers');
insert into items values (235, 'Dragon Scale');
insert into items values (236, 'Light Ball');
insert into items values (237, 'Soft Sand');
insert into items values (238, 'Hard Stone');
insert into items values (239, 'Miracle Seed');
insert into items values (240, 'Black Glasses');
insert into items values (241, 'Black Belt');
insert into items values (242, 'Magnet');
insert into items values (243, 'Mystic Water');
insert into items values (244, 'Sharp Beak');
insert into items values (245, 'Poison Barb');
insert into items values (246, 'Never-Melt Ice');
insert into items values (247, 'Spell Tag');
insert into items values (248, 'Twisted Spoon');
insert into items values (249, 'Charcoal');
insert into items values (250, 'Dragon Fang');
insert into items values (251, 'Silk Scarf');
insert into items values (252, 'Upgrade');
insert into items values (253, 'Shell Bell');
insert into items values (254, 'Sea Incense');
insert into items values (255, 'Lax Incense');
insert into items values (256, 'Lucky Punch');
insert into items values (257, 'Metal Powder');
insert into items values (258, 'Thick Club');
insert into items values (259, 'Leek');
insert into items values (260, 'Red Scarf');
insert into items values (261, 'Blue Scarf');
insert into items values (262, 'Pink Scarf');
insert into items values (263, 'Green Scarf');
insert into items values (264, 'Yellow Scarf');
insert into items values (265, 'Wide Lens');
insert into items values (266, 'Muscle Band');
insert into items values (267, 'Wise Glasses');
insert into items values (268, 'Expert Belt');
insert into items values (269, 'Light Clay');
insert into items values (270, 'Life Orb');
insert into items values (271, 'Power Herb');
insert into items values (272, 'Toxic Orb');
insert into items values (273, 'Flame Orb');
insert into items values (274, 'Quick Powder');
insert into items values (275, 'Focus Sash');
insert into items values (276, 'Zoom Lens');
insert into items values (277, 'Metronome');
insert into items values (278, 'Iron Ball');
insert into items values (279, 'Lagging Tail');
insert into items values (280, 'Destiny Knot');
insert into items values (281, 'Black Sludge');
insert into items values (282, 'Icy Rock');
insert into items values (283, 'Smooth Rock');
insert into items values (284, 'Heat Rock');
insert into items values (285, 'Damp Rock');
insert into items values (286, 'Grip Claw');
insert into items values (287, 'Choice Scarf');
insert into items values (288, 'Sticky Barb');
insert into items values (289, 'Power Bracer');
insert into items values (290, 'Power Belt');
insert into items values (291, 'Power Lens');
insert into items values (292, 'Power Band');
insert into items values (293, 'Power Anklet');
insert into items values (294, 'Power Weight');
insert into items values (295, 'Shed Shell');
insert into items values (296, 'Big Root');
insert into items values (297, 'Choice Specs');
insert into items values (298, 'Flame Plate');
insert into items values (299, 'Splash Plate');
insert into items values (300, 'Zap Plate');
insert into items values (301, 'Meadow Plate');
insert into items values (302, 'Icicle Plate');
insert into items values (303, 'Fist Plate');
insert into items values (304, 'Toxic Plate');
insert into items values (305, 'Earth Plate');
insert into items values (306, 'Sky Plate');
insert into items values (307, 'Mind Plate');
insert into items values (308, 'Insect Plate');
insert into items values (309, 'Stone Plate');
insert into items values (310, 'Spooky Plate');
insert into items values (311, 'Draco Plate');
insert into items values (312, 'Dread Plate');
insert into items values (313, 'Iron Plate');
insert into items values (314, 'Odd Incense');
insert into items values (315, 'Rock Incense');
insert into items values (316, 'Full Incense');
insert into items values (317, 'Wave Incense');
insert into items values (318, 'Rose Incense');
insert into items values (319, 'Luck Incense');
insert into items values (320, 'Pure Incense');
insert into items values (321, 'Protector');
insert into items values (322, 'Electirizer');
insert into items values (323, 'Magmarizer');
insert into items values (324, 'Dubious Disc');
insert into items values (325, 'Reaper Cloth');
insert into items values (326, 'Razor Claw');
insert into items values (327, 'Razor Fang');
insert into items values (328, 'TM Normal');
insert into items values (329, 'TM Normal');
insert into items values (330, 'TM Normal');
insert into items values (331, 'TM Normal');
insert into items values (332, 'TM Normal');
insert into items values (333, 'TM Normal');
insert into items values (334, 'TM Normal');
insert into items values (335, 'TM Normal');
insert into items values (336, 'TM Normal');
insert into items values (337, 'TM Normal');
insert into items values (338, 'TM Normal');
insert into items values (339, 'TM Normal');
insert into items values (340, 'TM Normal');
insert into items values (341, 'TM Normal');
insert into items values (342, 'TM Normal');
insert into items values (343, 'TM Normal');
insert into items values (344, 'TM Normal');
insert into items values (345, 'TM Normal');
insert into items values (346, 'TM Normal');
insert into items values (347, 'TM Normal');
insert into items values (348, 'TM Normal');
insert into items values (349, 'TM Normal');
insert into items values (350, 'TM Normal');
insert into items values (351, 'TM Normal');
insert into items values (352, 'TM Normal');
insert into items values (353, 'TM Normal');
insert into items values (354, 'TM Normal');
insert into items values (355, 'TM Normal');
insert into items values (356, 'TM Normal');
insert into items values (357, 'TM Normal');
insert into items values (358, 'TM Normal');
insert into items values (359, 'TM Normal');
insert into items values (360, 'TM Normal');
insert into items values (361, 'TM Normal');
insert into items values (362, 'TM Normal');
insert into items values (363, 'TM Normal');
insert into items values (364, 'TM Normal');
insert into items values (365, 'TM Normal');
insert into items values (366, 'TM Normal');
insert into items values (367, 'TM Normal');
insert into items values (368, 'TM Normal');
insert into items values (369, 'TM Normal');
insert into items values (370, 'TM Normal');
insert into items values (371, 'TM Normal');
insert into items values (372, 'TM Normal');
insert into items values (373, 'TM Normal');
insert into items values (374, 'TM Normal');
insert into items values (375, 'TM Normal');
insert into items values (376, 'TM Normal');
insert into items values (377, 'TM Normal');
insert into items values (378, 'TM Normal');
insert into items values (379, 'TM Normal');
insert into items values (380, 'TM Normal');
insert into items values (381, 'TM Normal');
insert into items values (382, 'TM Normal');
insert into items values (383, 'TM Normal');
insert into items values (384, 'TM Normal');
insert into items values (385, 'TM Normal');
insert into items values (386, 'TM Normal');
insert into items values (387, 'TM Normal');
insert into items values (388, 'TM Normal');
insert into items values (389, 'TM Normal');
insert into items values (390, 'TM Normal');
insert into items values (391, 'TM Normal');
insert into items values (392, 'TM Normal');
insert into items values (393, 'TM Normal');
insert into items values (394, 'TM Normal');
insert into items values (395, 'TM Normal');
insert into items values (396, 'TM Normal');
insert into items values (397, 'TM Normal');
insert into items values (398, 'TM Normal');
insert into items values (399, 'TM Normal');
insert into items values (400, 'TM Normal');
insert into items values (401, 'TM Normal');
insert into items values (402, 'TM Normal');
insert into items values (403, 'TM Normal');
insert into items values (404, 'TM Normal');
insert into items values (405, 'TM Normal');
insert into items values (406, 'TM Normal');
insert into items values (407, 'TM Normal');
insert into items values (408, 'TM Normal');
insert into items values (409, 'TM Normal');
insert into items values (410, 'TM Normal');
insert into items values (411, 'TM Normal');
insert into items values (412, 'TM Normal');
insert into items values (413, 'TM Normal');
insert into items values (414, 'TM Normal');
insert into items values (415, 'TM Normal');
insert into items values (416, 'TM Normal');
insert into items values (417, 'TM Normal');
insert into items values (418, 'TM Normal');
insert into items values (419, 'TM Normal');
insert into items values (420, 'TM Normal');
insert into items values (421, 'TM Normal');
insert into items values (422, 'TM Normal');
insert into items values (423, 'TM Normal');
insert into items values (424, 'TM Normal');
insert into items values (425, 'TM Normal');
insert into items values (426, 'TM Normal');
insert into items values (427, 'TM Normal');
insert into items values (428, 'Explorer Kit');
insert into items values (429, 'Loot Sack');
insert into items values (430, 'Rule Book');
insert into items values (431, 'Poké Radar');
insert into items values (432, 'Point Card');
insert into items values (433, 'Guidebook');
insert into items values (434, 'Sticker Case');
insert into items values (435, 'Fashion Case');
insert into items values (436, 'Sticker Bag');
insert into items values (437, 'Pal Pad');
insert into items values (438, 'Works Key');
insert into items values (439, 'Old Charm');
insert into items values (440, 'Galactic Key');
insert into items values (441, 'Red Chain');
insert into items values (442, 'Town Map');
insert into items values (443, 'Vs. Seeker');
insert into items values (444, 'Coin Case');
insert into items values (445, 'Old Rod');
insert into items values (446, 'Good Rod');
insert into items values (447, 'Super Rod');
insert into items values (448, 'Sprayduck');
insert into items values (449, 'Poffin Case');
insert into items values (450, 'Bike');
insert into items values (451, 'Suite Key');
insert into items values (452, 'Oak''s Letter');
insert into items values (453, 'Lunar Feather');
insert into items values (454, 'Member Card');
insert into items values (455, 'Azure Flute');
insert into items values (456, 'S.S. Ticket');
insert into items values (457, 'Contest Pass');
insert into items values (458, 'Magma Stone');
insert into items values (459, 'Parcel');
insert into items values (460, 'Coupon 1');
insert into items values (461, 'Coupon 2');
insert into items values (462, 'Coupon 3');
insert into items values (463, 'Storage Key');
insert into items values (464, 'Secret Medicine');
insert into items values (465, 'Vs. Recorder');
insert into items values (466, 'Gracidea');
insert into items values (467, 'Secret Key');
insert into items values (468, 'Apricorn Box');
insert into items values (469, 'Unown Report');
insert into items values (470, 'Berry Pots');
insert into items values (471, 'Dowsing Machine');
insert into items values (472, 'Blue Card');
insert into items values (473, 'Slowpoke Tail');
insert into items values (474, 'Clear Bell');
insert into items values (475, 'Card Key');
insert into items values (476, 'Basement Key');
insert into items values (477, 'Squirt Bottle ');
insert into items values (478, 'Red Scale');
insert into items values (479, 'Lost Item');
insert into items values (480, 'Pass');
insert into items values (481, 'Machine Part');
insert into items values (482, 'Silver Feather');
insert into items values (483, 'Rainbow Feather');
insert into items values (484, 'Mystery Egg');
insert into items values (485, 'Red Apricorn');
insert into items values (486, 'Blue Apricorn');
insert into items values (487, 'Yellow Apricorn');
insert into items values (488, 'Green Apricorn');
insert into items values (489, 'Pink Apricorn');
insert into items values (490, 'White Apricorn');
insert into items values (491, 'Black Apricorn');
insert into items values (492, 'Fast Ball');
insert into items values (493, 'Level Ball');
insert into items values (494, 'Lure Ball');
insert into items values (495, 'Heavy Ball');
insert into items values (496, 'Love Ball');
insert into items values (497, 'Friend Ball');
insert into items values (498, 'Moon Ball');
insert into items values (499, 'Sport Ball');
insert into items values (500, 'Park Ball');