insert into items values (1, 'Master Ball');
insert into items values (2, 'Ultra Ball');
insert into items values (3, 'Great Ball');
insert into items values (4, 'Poké Ball');
insert into items values (5, 'Safari Ball');
insert into items values (6, 'Net Ball');
insert into items values (7, 'Dive Ball');
insert into items values (8, 'Nest Ball');
insert into items values (9, 'Repeat Ball');
insert into items values (10, 'Timer Ball');
insert into items values (11, 'Luxury Ball');
insert into items values (12, 'Premier Ball');
insert into items values (13, 'Dusk Ball');
insert into items values (14, 'Heal Ball');
insert into items values (15, 'Quick Ball');
insert into items values (16, 'Cherish Ball');
insert into items values (17, 'Potion');
insert into items values (18, 'Antidote');
insert into items values (19, 'Burn Heal');
insert into items values (20, 'Ice Heal');
insert into items values (21, 'Awakening');
insert into items values (22, 'Paralyze Heal');
insert into items values (23, 'Full Restore');
insert into items values (24, 'Max Potion');
insert into items values (25, 'Hyper Potion');
insert into items values (26, 'Super Potion');
insert into items values (27, 'Full Heal');
insert into items values (28, 'Revive');
insert into items values (29, 'Max Revive');
insert into items values (30, 'Fresh Water');
insert into items values (31, 'Soda Pop');
insert into items values (32, 'Lemonade');
insert into items values (33, 'Moomoo Milk');
insert into items values (34, 'Energy Powder');
insert into items values (35, 'Energy Root');
insert into items values (36, 'Heal Powder');
insert into items values (37, 'Revival Herb');
insert into items values (38, 'Ether');
insert into items values (39, 'Max Ether');
insert into items values (40, 'Elixir');
insert into items values (41, 'Max Elixir');
insert into items values (42, 'Lava Cookie');
insert into items values (43, 'Berry Juice');
insert into items values (44, 'Sacred Ash');
insert into items values (45, 'HP Up');
insert into items values (46, 'Protein');
insert into items values (47, 'Iron');
insert into items values (48, 'Carbos');
insert into items values (49, 'Calcium');
insert into items values (50, 'Rare Candy');
insert into items values (51, 'PP Up');
insert into items values (52, 'Zinc');
insert into items values (53, 'PP Max');
insert into items values (54, 'Old Gateau');
insert into items values (55, 'Guard Spec.');
insert into items values (56, 'Dire Hit');
insert into items values (57, 'X Attack');
insert into items values (58, 'X Defense');
insert into items values (59, 'X Speed');
insert into items values (60, 'X Accuracy');
insert into items values (61, 'X Sp. Atk');
insert into items values (62, 'X Sp. Def');
insert into items values (63, 'Poké Doll');
insert into items values (64, 'Fluffy Tail');
insert into items values (65, 'Blue Flute');
insert into items values (66, 'Yellow Flute');
insert into items values (67, 'Red Flute');
insert into items values (68, 'Black Flute');
insert into items values (69, 'White Flute');
insert into items values (70, 'Shoal Salt');
insert into items values (71, 'Shoal Shell');
insert into items values (72, 'Red Shard');
insert into items values (73, 'Blue Shard');
insert into items values (74, 'Yellow Shard');
insert into items values (75, 'Green Shard');
insert into items values (76, 'Super Repel');
insert into items values (77, 'Max Repel');
insert into items values (78, 'Escape Rope');
insert into items values (79, 'Repel');
insert into items values (80, 'Sun Stone');
insert into items values (81, 'Moon Stone');
insert into items values (82, 'Fire Stone');
insert into items values (83, 'Thunder Stone');
insert into items values (84, 'Water Stone');
insert into items values (85, 'Leaf Stone');
insert into items values (86, 'Tiny Mushroom');
insert into items values (87, 'Big Mushroom');
insert into items values (88, 'Pearl');
insert into items values (89, 'Big Pearl');
insert into items values (90, 'Stardust');
insert into items values (91, 'Star Piece');
insert into items values (92, 'Nugget');
insert into items values (93, 'Heart Scale');
insert into items values (94, 'Honey');
insert into items values (95, 'Growth Mulch');
insert into items values (96, 'Damp Mulch');
insert into items values (97, 'Stable Mulch');
insert into items values (98, 'Gooey Mulch');
insert into items values (99, 'Root Fossil');
insert into items values (100, 'Claw Fossil');
insert into items values (101, 'Helix Fossil');
insert into items values (102, 'Dome Fossil');
insert into items values (103, 'Old Amber');
insert into items values (104, 'Armor Fossil');
insert into items values (105, 'Skull Fossil');
insert into items values (106, 'Rare Bone');
insert into items values (107, 'Shiny Stone');
insert into items values (108, 'Dusk Stone');
insert into items values (109, 'Dawn Stone');
insert into items values (110, 'Oval Stone');
insert into items values (111, 'Odd Keystone');
insert into items values (112, 'Griseous Orb');
insert into items values (113, 'Tea');
insert into items values (114, 'Unknown');
insert into items values (115, 'Autograph');
insert into items values (116, 'Douse Drive');
insert into items values (117, 'Shock Drive');
insert into items values (118, 'Burn Drive');
insert into items values (119, 'Chill Drive');
insert into items values (120, 'Unknown');
insert into items values (121, 'Pokémon Box');
insert into items values (122, 'Medicine Pocket');
insert into items values (123, 'TM Case');
insert into items values (124, 'Candy Jar');
insert into items values (125, 'Power-Up Pocket');
insert into items values (126, 'Clothing Trunk');
insert into items values (127, 'Catching Pocket');
insert into items values (128, 'Battle Pocket');
insert into items values (129, 'Unknown');
insert into items values (130, 'Unknown');
insert into items values (131, 'Unknown');
insert into items values (132, 'Unknown');
insert into items values (133, 'Unknown');
insert into items values (134, 'Sweet Heart');
insert into items values (135, 'Adamant Orb');
insert into items values (136, 'Lustrous Orb');
insert into items values (137, 'Greet Mail');
insert into items values (138, 'Favored Mail');
insert into items values (139, 'RSVP Mail');
insert into items values (140, 'Thanks Mail');
insert into items values (141, 'Inquiry Mail');
insert into items values (142, 'Like Mail');
insert into items values (143, 'Reply Mail');
insert into items values (144, 'Bridge Mail S');
insert into items values (145, 'Bridge Mail D');
insert into items values (146, 'Bridge Mail T');
insert into items values (147, 'Bridge Mail V');
insert into items values (148, 'Bridge Mail M');
insert into items values (149, 'Cheri Berry');
insert into items values (150, 'Chesto Berry');
insert into items values (151, 'Pecha Berry');
insert into items values (152, 'Rawst Berry');
insert into items values (153, 'Aspear Berry');
insert into items values (154, 'Leppa Berry');
insert into items values (155, 'Oran Berry');
insert into items values (156, 'Persim Berry');
insert into items values (157, 'Lum Berry');
insert into items values (158, 'Sitrus Berry');
insert into items values (159, 'Figy Berry');
insert into items values (160, 'Wiki Berry');
insert into items values (161, 'Mago Berry');
insert into items values (162, 'Aguav Berry');
insert into items values (163, 'Iapapa Berry');
insert into items values (164, 'Razz Berry');
insert into items values (165, 'Bluk Berry');
insert into items values (166, 'Nanab Berry');
insert into items values (167, 'Wepear Berry');
insert into items values (168, 'Pinap Berry');
insert into items values (169, 'Pomeg Berry');
insert into items values (170, 'Kelpsy Berry');
insert into items values (171, 'Qualot Berry');
insert into items values (172, 'Hondew Berry');
insert into items values (173, 'Grepa Berry');
insert into items values (174, 'Tamato Berry');
insert into items values (175, 'Cornn Berry');
insert into items values (176, 'Magost Berry');
insert into items values (177, 'Rabuta Berry');
insert into items values (178, 'Nomel Berry');
insert into items values (179, 'Spelon Berry');
insert into items values (180, 'Pamtre Berry');
insert into items values (181, 'Watmel Berry');
insert into items values (182, 'Durin Berry');
insert into items values (183, 'Belue Berry');
insert into items values (184, 'Occa Berry');
insert into items values (185, 'Passho Berry');
insert into items values (186, 'Wacan Berry');
insert into items values (187, 'Rindo Berry');
insert into items values (188, 'Yache Berry');
insert into items values (189, 'Chople Berry');
insert into items values (190, 'Kebia Berry');
insert into items values (191, 'Shuca Berry');
insert into items values (192, 'Coba Berry');
insert into items values (193, 'Payapa Berry');
insert into items values (194, 'Tanga Berry');
insert into items values (195, 'Charti Berry');
insert into items values (196, 'Kasib Berry');
insert into items values (197, 'Haban Berry');
insert into items values (198, 'Colbur Berry');
insert into items values (199, 'Babiri Berry');
insert into items values (200, 'Chilan Berry');
insert into items values (201, 'Liechi Berry');
insert into items values (202, 'Ganlon Berry');
insert into items values (203, 'Salac Berry');
insert into items values (204, 'Petaya Berry');
insert into items values (205, 'Apicot Berry');
insert into items values (206, 'Lansat Berry');
insert into items values (207, 'Starf Berry');
insert into items values (208, 'Enigma Berry');
insert into items values (209, 'Micle Berry');
insert into items values (210, 'Custap Berry');
insert into items values (211, 'Jaboca Berry');
insert into items values (212, 'Rowap Berry');
insert into items values (213, 'Bright Powder');
insert into items values (214, 'White Herb');
insert into items values (215, 'Macho Brace');
insert into items values (216, 'Exp. Share');
insert into items values (217, 'Quick Claw');
insert into items values (218, 'Soothe Bell');
insert into items values (219, 'Mental Herb');
insert into items values (220, 'Choice Band');
insert into items values (221, 'King''s Rock');
insert into items values (222, 'Silver Powder');
insert into items values (223, 'Amulet Coin');
insert into items values (224, 'Cleanse Tag');
insert into items values (225, 'Soul Dew');
insert into items values (226, 'Deep Sea Tooth');
insert into items values (227, 'Deep Sea Scale');
insert into items values (228, 'Smoke Ball');
insert into items values (229, 'Everstone');
insert into items values (230, 'Focus Band');
insert into items values (231, 'Lucky Egg');
insert into items values (232, 'Scope Lens');
insert into items values (233, 'Metal Coat');
insert into items values (234, 'Leftovers');
insert into items values (235, 'Dragon Scale');
insert into items values (236, 'Light Ball');
insert into items values (237, 'Soft Sand');
insert into items values (238, 'Hard Stone');
insert into items values (239, 'Miracle Seed');
insert into items values (240, 'Black Glasses');
insert into items values (241, 'Black Belt');
insert into items values (242, 'Magnet');
insert into items values (243, 'Mystic Water');
insert into items values (244, 'Sharp Beak');
insert into items values (245, 'Poison Barb');
insert into items values (246, 'Never-Melt Ice');
insert into items values (247, 'Spell Tag');
insert into items values (248, 'Twisted Spoon');
insert into items values (249, 'Charcoal');
insert into items values (250, 'Dragon Fang');
insert into items values (251, 'Silk Scarf');
insert into items values (252, 'Upgrade');
insert into items values (253, 'Shell Bell');
insert into items values (254, 'Sea Incense');
insert into items values (255, 'Lax Incense');
insert into items values (256, 'Lucky Punch');
insert into items values (257, 'Metal Powder');
insert into items values (258, 'Thick Club');
insert into items values (259, 'Leek');
insert into items values (260, 'Red Scarf');
insert into items values (261, 'Blue Scarf');
insert into items values (262, 'Pink Scarf');
insert into items values (263, 'Green Scarf');
insert into items values (264, 'Yellow Scarf');
insert into items values (265, 'Wide Lens');
insert into items values (266, 'Muscle Band');
insert into items values (267, 'Wise Glasses');
insert into items values (268, 'Expert Belt');
insert into items values (269, 'Light Clay');
insert into items values (270, 'Life Orb');
insert into items values (271, 'Power Herb');
insert into items values (272, 'Toxic Orb');
insert into items values (273, 'Flame Orb');
insert into items values (274, 'Quick Powder');
insert into items values (275, 'Focus Sash');
insert into items values (276, 'Zoom Lens');
insert into items values (277, 'Metronome');
insert into items values (278, 'Iron Ball');
insert into items values (279, 'Lagging Tail');
insert into items values (280, 'Destiny Knot');
insert into items values (281, 'Black Sludge');
insert into items values (282, 'Icy Rock');
insert into items values (283, 'Smooth Rock');
insert into items values (284, 'Heat Rock');
insert into items values (285, 'Damp Rock');
insert into items values (286, 'Grip Claw');
insert into items values (287, 'Choice Scarf');
insert into items values (288, 'Sticky Barb');
insert into items values (289, 'Power Bracer');
insert into items values (290, 'Power Belt');
insert into items values (291, 'Power Lens');
insert into items values (292, 'Power Band');
insert into items values (293, 'Power Anklet');
insert into items values (294, 'Power Weight');
insert into items values (295, 'Shed Shell');
insert into items values (296, 'Big Root');
insert into items values (297, 'Choice Specs');
insert into items values (298, 'Flame Plate');
insert into items values (299, 'Splash Plate');
insert into items values (300, 'Zap Plate');