insert into items values (1, 'Master Ball');
insert into items values (2, 'Ultra Ball');
insert into items values (3, 'Great Ball');
insert into items values (4, 'Poké Ball');
insert into items values (5, 'Safari Ball');
insert into items values (6, 'Net Ball');
insert into items values (7, 'Dive Ball');
insert into items values (8, 'Nest Ball');
insert into items values (9, 'Repeat Ball');
insert into items values (10, 'Timer Ball');
insert into items values (11, 'Luxury Ball');
insert into items values (12, 'Premier Ball');
insert into items values (13, 'Dusk Ball');
insert into items values (14, 'Heal Ball');
insert into items values (15, 'Quick Ball');
insert into items values (16, 'Cherish Ball');
insert into items values (17, 'Potion');
insert into items values (18, 'Antidote');
insert into items values (19, 'Burn Heal');
insert into items values (20, 'Ice Heal');
insert into items values (21, 'Awakening');
insert into items values (22, 'Paralyze Heal');
insert into items values (23, 'Full Restore');
insert into items values (24, 'Max Potion');
insert into items values (25, 'Hyper Potion');
insert into items values (26, 'Super Potion');
insert into items values (27, 'Full Heal');
insert into items values (28, 'Revive');
insert into items values (29, 'Max Revive');
insert into items values (30, 'Fresh Water');
insert into items values (31, 'Soda Pop');
insert into items values (32, 'Lemonade');
insert into items values (33, 'Moomoo Milk');
insert into items values (34, 'Energy Powder');
insert into items values (35, 'Energy Root');
insert into items values (36, 'Heal Powder');
insert into items values (37, 'Revival Herb');
insert into items values (38, 'Ether');
insert into items values (39, 'Max Ether');
insert into items values (40, 'Elixir');
insert into items values (41, 'Max Elixir');
insert into items values (42, 'Lava Cookie');
insert into items values (43, 'Berry Juice');
insert into items values (44, 'Sacred Ash');
insert into items values (45, 'HP Up');
insert into items values (46, 'Protein');
insert into items values (47, 'Iron');
insert into items values (48, 'Carbos');
insert into items values (49, 'Calcium');
insert into items values (50, 'Rare Candy');
insert into items values (51, 'PP Up');
insert into items values (52, 'Zinc');
insert into items values (53, 'PP Max');
insert into items values (54, 'Old Gateau');
insert into items values (55, 'Guard Spec.');
insert into items values (56, 'Dire Hit');
insert into items values (57, 'X Attack');
insert into items values (58, 'X Defense');
insert into items values (59, 'X Speed');
insert into items values (60, 'X Accuracy');
insert into items values (61, 'X Sp. Atk');
insert into items values (62, 'X Sp. Def');
insert into items values (63, 'Poké Doll');
insert into items values (64, 'Fluffy Tail');
insert into items values (65, 'Blue Flute');
insert into items values (66, 'Yellow Flute');
insert into items values (67, 'Red Flute');
insert into items values (68, 'Black Flute');
insert into items values (69, 'White Flute');
insert into items values (70, 'Shoal Salt');
insert into items values (71, 'Shoal Shell');
insert into items values (72, 'Red Shard');
insert into items values (73, 'Blue Shard');
insert into items values (74, 'Yellow Shard');
insert into items values (75, 'Green Shard');
insert into items values (76, 'Super Repel');
insert into items values (77, 'Max Repel');
insert into items values (78, 'Escape Rope');
insert into items values (79, 'Repel');
insert into items values (80, 'Sun Stone');
insert into items values (81, 'Moon Stone');
insert into items values (82, 'Fire Stone');
insert into items values (83, 'Thunder Stone');
insert into items values (84, 'Water Stone');
insert into items values (85, 'Leaf Stone');
insert into items values (86, 'Tiny Mushroom');
insert into items values (87, 'Big Mushroom');
insert into items values (88, 'Pearl');
insert into items values (89, 'Big Pearl');
insert into items values (90, 'Stardust');
insert into items values (91, 'Star Piece');
insert into items values (92, 'Nugget');
insert into items values (93, 'Heart Scale');
insert into items values (94, 'Honey');
insert into items values (95, 'Growth Mulch');
insert into items values (96, 'Damp Mulch');
insert into items values (97, 'Stable Mulch');
insert into items values (98, 'Gooey Mulch');
insert into items values (99, 'Root Fossil');
insert into items values (100, 'Claw Fossil');
insert into items values (101, 'Helix Fossil');
insert into items values (102, 'Dome Fossil');
insert into items values (103, 'Old Amber');
insert into items values (104, 'Armor Fossil');
insert into items values (105, 'Skull Fossil');
insert into items values (106, 'Rare Bone');
insert into items values (107, 'Shiny Stone');
insert into items values (108, 'Dusk Stone');
insert into items values (109, 'Dawn Stone');
insert into items values (110, 'Oval Stone');
insert into items values (111, 'Odd Keystone');
insert into items values (112, 'Griseous Orb');
insert into items values (113, 'Tea');
insert into items values (114, 'Unknown');
insert into items values (115, 'Autograph');
insert into items values (116, 'Douse Drive');
insert into items values (117, 'Shock Drive');
insert into items values (118, 'Burn Drive');
insert into items values (119, 'Chill Drive');
insert into items values (120, 'Unknown');
insert into items values (121, 'Pokémon Box');
insert into items values (122, 'Medicine Pocket');
insert into items values (123, 'TM Case');
insert into items values (124, 'Candy Jar');
insert into items values (125, 'Power-Up Pocket');
insert into items values (126, 'Clothing Trunk');
insert into items values (127, 'Catching Pocket');
insert into items values (128, 'Battle Pocket');
insert into items values (129, 'Unknown');
insert into items values (130, 'Unknown');
insert into items values (131, 'Unknown');
insert into items values (132, 'Unknown');
insert into items values (133, 'Unknown');
insert into items values (134, 'Sweet Heart');
insert into items values (135, 'Adamant Orb');
insert into items values (136, 'Lustrous Orb');
insert into items values (137, 'Greet Mail');
insert into items values (138, 'Favored Mail');
insert into items values (139, 'RSVP Mail');
insert into items values (140, 'Thanks Mail');
insert into items values (141, 'Inquiry Mail');
insert into items values (142, 'Like Mail');
insert into items values (143, 'Reply Mail');
insert into items values (144, 'Bridge Mail S');
insert into items values (145, 'Bridge Mail D');
insert into items values (146, 'Bridge Mail T');
insert into items values (147, 'Bridge Mail V');
insert into items values (148, 'Bridge Mail M');
insert into items values (149, 'Cheri Berry');
insert into items values (150, 'Chesto Berry');
insert into items values (151, 'Pecha Berry');
insert into items values (152, 'Rawst Berry');
insert into items values (153, 'Aspear Berry');
insert into items values (154, 'Leppa Berry');
insert into items values (155, 'Oran Berry');
insert into items values (156, 'Persim Berry');
insert into items values (157, 'Lum Berry');
insert into items values (158, 'Sitrus Berry');
insert into items values (159, 'Figy Berry');
insert into items values (160, 'Wiki Berry');
insert into items values (161, 'Mago Berry');
insert into items values (162, 'Aguav Berry');
insert into items values (163, 'Iapapa Berry');
insert into items values (164, 'Razz Berry');
insert into items values (165, 'Bluk Berry');
insert into items values (166, 'Nanab Berry');
insert into items values (167, 'Wepear Berry');
insert into items values (168, 'Pinap Berry');
insert into items values (169, 'Pomeg Berry');
insert into items values (170, 'Kelpsy Berry');
insert into items values (171, 'Qualot Berry');
insert into items values (172, 'Hondew Berry');
insert into items values (173, 'Grepa Berry');
insert into items values (174, 'Tamato Berry');
insert into items values (175, 'Cornn Berry');
insert into items values (176, 'Magost Berry');
insert into items values (177, 'Rabuta Berry');
insert into items values (178, 'Nomel Berry');
insert into items values (179, 'Spelon Berry');
insert into items values (180, 'Pamtre Berry');
insert into items values (181, 'Watmel Berry');
insert into items values (182, 'Durin Berry');
insert into items values (183, 'Belue Berry');
insert into items values (184, 'Occa Berry');
insert into items values (185, 'Passho Berry');
insert into items values (186, 'Wacan Berry');
insert into items values (187, 'Rindo Berry');
insert into items values (188, 'Yache Berry');
insert into items values (189, 'Chople Berry');
insert into items values (190, 'Kebia Berry');
insert into items values (191, 'Shuca Berry');
insert into items values (192, 'Coba Berry');
insert into items values (193, 'Payapa Berry');
insert into items values (194, 'Tanga Berry');
insert into items values (195, 'Charti Berry');
insert into items values (196, 'Kasib Berry');
insert into items values (197, 'Haban Berry');
insert into items values (198, 'Colbur Berry');
insert into items values (199, 'Babiri Berry');
insert into items values (200, 'Chilan Berry');
insert into items values (201, 'Liechi Berry');
insert into items values (202, 'Ganlon Berry');
insert into items values (203, 'Salac Berry');
insert into items values (204, 'Petaya Berry');
insert into items values (205, 'Apicot Berry');
insert into items values (206, 'Lansat Berry');
insert into items values (207, 'Starf Berry');
insert into items values (208, 'Enigma Berry');
insert into items values (209, 'Micle Berry');
insert into items values (210, 'Custap Berry');
insert into items values (211, 'Jaboca Berry');
insert into items values (212, 'Rowap Berry');
insert into items values (213, 'Bright Powder');
insert into items values (214, 'White Herb');
insert into items values (215, 'Macho Brace');
insert into items values (216, 'Exp. Share');
insert into items values (217, 'Quick Claw');
insert into items values (218, 'Soothe Bell');
insert into items values (219, 'Mental Herb');
insert into items values (220, 'Choice Band');
insert into items values (221, 'King''s Rock');
insert into items values (222, 'Silver Powder');
insert into items values (223, 'Amulet Coin');
insert into items values (224, 'Cleanse Tag');
insert into items values (225, 'Soul Dew');
insert into items values (226, 'Deep Sea Tooth');
insert into items values (227, 'Deep Sea Scale');
insert into items values (228, 'Smoke Ball');
insert into items values (229, 'Everstone');
insert into items values (230, 'Focus Band');
insert into items values (231, 'Lucky Egg');
insert into items values (232, 'Scope Lens');
insert into items values (233, 'Metal Coat');
insert into items values (234, 'Leftovers');
insert into items values (235, 'Dragon Scale');
insert into items values (236, 'Light Ball');
insert into items values (237, 'Soft Sand');
insert into items values (238, 'Hard Stone');
insert into items values (239, 'Miracle Seed');
insert into items values (240, 'Black Glasses');
insert into items values (241, 'Black Belt');
insert into items values (242, 'Magnet');
insert into items values (243, 'Mystic Water');
insert into items values (244, 'Sharp Beak');
insert into items values (245, 'Poison Barb');
insert into items values (246, 'Never-Melt Ice');
insert into items values (247, 'Spell Tag');
insert into items values (248, 'Twisted Spoon');
insert into items values (249, 'Charcoal');
insert into items values (250, 'Dragon Fang');
insert into items values (251, 'Silk Scarf');
insert into items values (252, 'Upgrade');
insert into items values (253, 'Shell Bell');
insert into items values (254, 'Sea Incense');
insert into items values (255, 'Lax Incense');
insert into items values (256, 'Lucky Punch');
insert into items values (257, 'Metal Powder');
insert into items values (258, 'Thick Club');
insert into items values (259, 'Leek');
insert into items values (260, 'Red Scarf');
insert into items values (261, 'Blue Scarf');
insert into items values (262, 'Pink Scarf');
insert into items values (263, 'Green Scarf');
insert into items values (264, 'Yellow Scarf');
insert into items values (265, 'Wide Lens');
insert into items values (266, 'Muscle Band');
insert into items values (267, 'Wise Glasses');
insert into items values (268, 'Expert Belt');
insert into items values (269, 'Light Clay');
insert into items values (270, 'Life Orb');
insert into items values (271, 'Power Herb');
insert into items values (272, 'Toxic Orb');
insert into items values (273, 'Flame Orb');
insert into items values (274, 'Quick Powder');
insert into items values (275, 'Focus Sash');
insert into items values (276, 'Zoom Lens');
insert into items values (277, 'Metronome');
insert into items values (278, 'Iron Ball');
insert into items values (279, 'Lagging Tail');
insert into items values (280, 'Destiny Knot');
insert into items values (281, 'Black Sludge');
insert into items values (282, 'Icy Rock');
insert into items values (283, 'Smooth Rock');
insert into items values (284, 'Heat Rock');
insert into items values (285, 'Damp Rock');
insert into items values (286, 'Grip Claw');
insert into items values (287, 'Choice Scarf');
insert into items values (288, 'Sticky Barb');
insert into items values (289, 'Power Bracer');
insert into items values (290, 'Power Belt');
insert into items values (291, 'Power Lens');
insert into items values (292, 'Power Band');
insert into items values (293, 'Power Anklet');
insert into items values (294, 'Power Weight');
insert into items values (295, 'Shed Shell');
insert into items values (296, 'Big Root');
insert into items values (297, 'Choice Specs');
insert into items values (298, 'Flame Plate');
insert into items values (299, 'Splash Plate');
insert into items values (300, 'Zap Plate');
insert into items values (301, 'Meadow Plate');
insert into items values (302, 'Icicle Plate');
insert into items values (303, 'Fist Plate');
insert into items values (304, 'Toxic Plate');
insert into items values (305, 'Earth Plate');
insert into items values (306, 'Sky Plate');
insert into items values (307, 'Mind Plate');
insert into items values (308, 'Insect Plate');
insert into items values (309, 'Stone Plate');
insert into items values (310, 'Spooky Plate');
insert into items values (311, 'Draco Plate');
insert into items values (312, 'Dread Plate');
insert into items values (313, 'Iron Plate');
insert into items values (314, 'Odd Incense');
insert into items values (315, 'Rock Incense');
insert into items values (316, 'Full Incense');
insert into items values (317, 'Wave Incense');
insert into items values (318, 'Rose Incense');
insert into items values (319, 'Luck Incense');
insert into items values (320, 'Pure Incense');
insert into items values (321, 'Protector');
insert into items values (322, 'Electirizer');
insert into items values (323, 'Magmarizer');
insert into items values (324, 'Dubious Disc');
insert into items values (325, 'Reaper Cloth');
insert into items values (326, 'Razor Claw');
insert into items values (327, 'Razor Fang');
insert into items values (328, 'TM Normal');
insert into items values (329, 'TM Normal');
insert into items values (330, 'TM Normal');
insert into items values (331, 'TM Normal');
insert into items values (332, 'TM Normal');
insert into items values (333, 'TM Normal');
insert into items values (334, 'TM Normal');
insert into items values (335, 'TM Normal');
insert into items values (336, 'TM Normal');
insert into items values (337, 'TM Normal');
insert into items values (338, 'TM Normal');
insert into items values (339, 'TM Normal');
insert into items values (340, 'TM Normal');
insert into items values (341, 'TM Normal');
insert into items values (342, 'TM Normal');
insert into items values (343, 'TM Normal');
insert into items values (344, 'TM Normal');
insert into items values (345, 'TM Normal');
insert into items values (346, 'TM Normal');
insert into items values (347, 'TM Normal');
insert into items values (348, 'TM Normal');
insert into items values (349, 'TM Normal');
insert into items values (350, 'TM Normal');
insert into items values (351, 'TM Normal');
insert into items values (352, 'TM Normal');
insert into items values (353, 'TM Normal');
insert into items values (354, 'TM Normal');
insert into items values (355, 'TM Normal');
insert into items values (356, 'TM Normal');
insert into items values (357, 'TM Normal');
insert into items values (358, 'TM Normal');
insert into items values (359, 'TM Normal');
insert into items values (360, 'TM Normal');
insert into items values (361, 'TM Normal');
insert into items values (362, 'TM Normal');
insert into items values (363, 'TM Normal');
insert into items values (364, 'TM Normal');
insert into items values (365, 'TM Normal');
insert into items values (366, 'TM Normal');
insert into items values (367, 'TM Normal');
insert into items values (368, 'TM Normal');
insert into items values (369, 'TM Normal');
insert into items values (370, 'TM Normal');
insert into items values (371, 'TM Normal');
insert into items values (372, 'TM Normal');
insert into items values (373, 'TM Normal');
insert into items values (374, 'TM Normal');
insert into items values (375, 'TM Normal');
insert into items values (376, 'TM Normal');
insert into items values (377, 'TM Normal');
insert into items values (378, 'TM Normal');
insert into items values (379, 'TM Normal');
insert into items values (380, 'TM Normal');
insert into items values (381, 'TM Normal');
insert into items values (382, 'TM Normal');
insert into items values (383, 'TM Normal');
insert into items values (384, 'TM Normal');
insert into items values (385, 'TM Normal');
insert into items values (386, 'TM Normal');
insert into items values (387, 'TM Normal');
insert into items values (388, 'TM Normal');
insert into items values (389, 'TM Normal');
insert into items values (390, 'TM Normal');
insert into items values (391, 'TM Normal');
insert into items values (392, 'TM Normal');
insert into items values (393, 'TM Normal');
insert into items values (394, 'TM Normal');
insert into items values (395, 'TM Normal');
insert into items values (396, 'TM Normal');
insert into items values (397, 'TM Normal');
insert into items values (398, 'TM Normal');
insert into items values (399, 'TM Normal');
insert into items values (400, 'TM Normal');
insert into items values (401, 'TM Normal');
insert into items values (402, 'TM Normal');
insert into items values (403, 'TM Normal');
insert into items values (404, 'TM Normal');
insert into items values (405, 'TM Normal');
insert into items values (406, 'TM Normal');
insert into items values (407, 'TM Normal');
insert into items values (408, 'TM Normal');
insert into items values (409, 'TM Normal');
insert into items values (410, 'TM Normal');
insert into items values (411, 'TM Normal');
insert into items values (412, 'TM Normal');
insert into items values (413, 'TM Normal');
insert into items values (414, 'TM Normal');
insert into items values (415, 'TM Normal');
insert into items values (416, 'TM Normal');
insert into items values (417, 'TM Normal');
insert into items values (418, 'TM Normal');
insert into items values (419, 'TM Normal');
insert into items values (420, 'TM Normal');
insert into items values (421, 'TM Normal');
insert into items values (422, 'TM Normal');
insert into items values (423, 'TM Normal');
insert into items values (424, 'TM Normal');
insert into items values (425, 'TM Normal');
insert into items values (426, 'TM Normal');
insert into items values (427, 'TM Normal');
insert into items values (428, 'Explorer Kit');
insert into items values (429, 'Loot Sack');
insert into items values (430, 'Rule Book');
insert into items values (431, 'Poké Radar');
insert into items values (432, 'Point Card');
insert into items values (433, 'Guidebook');
insert into items values (434, 'Sticker Case');
insert into items values (435, 'Fashion Case');
insert into items values (436, 'Sticker Bag');
insert into items values (437, 'Pal Pad');
insert into items values (438, 'Works Key');
insert into items values (439, 'Old Charm');
insert into items values (440, 'Galactic Key');
insert into items values (441, 'Red Chain');
insert into items values (442, 'Town Map');
insert into items values (443, 'Vs. Seeker');
insert into items values (444, 'Coin Case');
insert into items values (445, 'Old Rod');
insert into items values (446, 'Good Rod');
insert into items values (447, 'Super Rod');
insert into items values (448, 'Sprayduck');
insert into items values (449, 'Poffin Case');
insert into items values (450, 'Bike');
insert into items values (451, 'Suite Key');
insert into items values (452, 'Oak''s Letter');
insert into items values (453, 'Lunar Feather');
insert into items values (454, 'Member Card');
insert into items values (455, 'Azure Flute');
insert into items values (456, 'S.S. Ticket');
insert into items values (457, 'Contest Pass');
insert into items values (458, 'Magma Stone');
insert into items values (459, 'Parcel');
insert into items values (460, 'Coupon 1');
insert into items values (461, 'Coupon 2');
insert into items values (462, 'Coupon 3');
insert into items values (463, 'Storage Key');
insert into items values (464, 'Secret Medicine');
insert into items values (465, 'Vs. Recorder');
insert into items values (466, 'Gracidea');
insert into items values (467, 'Secret Key');
insert into items values (468, 'Apricorn Box');
insert into items values (469, 'Unown Report');
insert into items values (470, 'Berry Pots');
insert into items values (471, 'Dowsing Machine');
insert into items values (472, 'Blue Card');
insert into items values (473, 'Slowpoke Tail');
insert into items values (474, 'Clear Bell');
insert into items values (475, 'Card Key');
insert into items values (476, 'Basement Key');
insert into items values (477, 'Squirt Bottle ');
insert into items values (478, 'Red Scale');
insert into items values (479, 'Lost Item');
insert into items values (480, 'Pass');
insert into items values (481, 'Machine Part');
insert into items values (482, 'Silver Feather');
insert into items values (483, 'Rainbow Feather');
insert into items values (484, 'Mystery Egg');
insert into items values (485, 'Red Apricorn');
insert into items values (486, 'Blue Apricorn');
insert into items values (487, 'Yellow Apricorn');
insert into items values (488, 'Green Apricorn');
insert into items values (489, 'Pink Apricorn');
insert into items values (490, 'White Apricorn');
insert into items values (491, 'Black Apricorn');
insert into items values (492, 'Fast Ball');
insert into items values (493, 'Level Ball');
insert into items values (494, 'Lure Ball');
insert into items values (495, 'Heavy Ball');
insert into items values (496, 'Love Ball');
insert into items values (497, 'Friend Ball');
insert into items values (498, 'Moon Ball');
insert into items values (499, 'Sport Ball');
insert into items values (500, 'Park Ball');
insert into items values (501, 'Photo Album');
insert into items values (502, 'GB Sounds');
insert into items values (503, 'Tidal Bell');
insert into items values (504, 'Rage Candy Bar');
insert into items values (505, 'Data Card');
insert into items values (506, 'Data Card');
insert into items values (507, 'Data Card');
insert into items values (508, 'Data Card');
insert into items values (509, 'Data Card');
insert into items values (510, 'Data Card');
insert into items values (511, 'Data Card');
insert into items values (512, 'Data Card');
insert into items values (513, 'Data Card');
insert into items values (514, 'Data Card');
insert into items values (515, 'Data Card');
insert into items values (516, 'Data Card');
insert into items values (517, 'Data Card');
insert into items values (518, 'Data Card');
insert into items values (519, 'Data Card');
insert into items values (520, 'Data Card');
insert into items values (521, 'Data Card');
insert into items values (522, 'Data Card');
insert into items values (523, 'Data Card');
insert into items values (524, 'Data Card');
insert into items values (525, 'Data Card');
insert into items values (526, 'Data Card');
insert into items values (527, 'Data Card');
insert into items values (528, 'Data Card');
insert into items values (529, 'Data Card');
insert into items values (530, 'Data Card');
insert into items values (531, 'Data Card');
insert into items values (532, 'Jade Orb');
insert into items values (533, 'Lock Capsule');
insert into items values (534, 'Red Orb');
insert into items values (535, 'Blue Orb');
insert into items values (536, 'Enigma Stone');
insert into items values (537, 'Prism Scale');
insert into items values (538, 'Eviolite');
insert into items values (539, 'Float Stone');
insert into items values (540, 'Rocky Helmet');
insert into items values (541, 'Air Balloon');
insert into items values (542, 'Red Card');
insert into items values (543, 'Ring Target');
insert into items values (544, 'Binding Band');
insert into items values (545, 'Absorb Bulb');
insert into items values (546, 'Cell Battery');
insert into items values (547, 'Eject Button');
insert into items values (548, 'Fire Gem');
insert into items values (549, 'Water Gem');
insert into items values (550, 'Electric Gem');
insert into items values (551, 'Grass Gem');
insert into items values (552, 'Ice Gem');
insert into items values (553, 'Fighting Gem');
insert into items values (554, 'Poison Gem');
insert into items values (555, 'Ground Gem');
insert into items values (556, 'Flying Gem');
insert into items values (557, 'Psychic Gem');
insert into items values (558, 'Bug Gem');
insert into items values (559, 'Rock Gem');
insert into items values (560, 'Ghost Gem');
insert into items values (561, 'Dragon Gem');
insert into items values (562, 'Dark Gem');
insert into items values (563, 'Steel Gem');
insert into items values (564, 'Normal Gem');
insert into items values (565, 'Health Feather');
insert into items values (566, 'Muscle Feather');
insert into items values (567, 'Resist Feather');
insert into items values (568, 'Genius Feather');
insert into items values (569, 'Clever Feather');
insert into items values (570, 'Swift Feather');
insert into items values (571, 'Pretty Feather');
insert into items values (572, 'Cover Fossil');
insert into items values (573, 'Plume Fossil');
insert into items values (574, 'Liberty Pass');
insert into items values (575, 'Pass Orb');
insert into items values (576, 'Dream Ball');
insert into items values (577, 'Poké Toy');
insert into items values (578, 'Prop Case');
insert into items values (579, 'Dragon Skull');
insert into items values (580, 'Balm Mushroom');
insert into items values (581, 'Big Nugget');
insert into items values (582, 'Pearl String');
insert into items values (583, 'Comet Shard');
insert into items values (584, 'Relic Copper');
insert into items values (585, 'Relic Silver');
insert into items values (586, 'Relic Gold');
insert into items values (587, 'Relic Vase');
insert into items values (588, 'Relic Band');
insert into items values (589, 'Relic Statue');
insert into items values (590, 'Relic Crown');
insert into items values (591, 'Casteliacone');
insert into items values (592, 'Dire Hit');
insert into items values (593, 'X Speed');
insert into items values (594, 'X Sp. Atk');
insert into items values (595, 'X Sp. Def');
insert into items values (596, 'X Defense');
insert into items values (597, 'X Attack');
insert into items values (598, 'X Accuracy');
insert into items values (599, 'X Speed');
insert into items values (600, 'X Sp. Atk');
insert into items values (601, 'X Sp. Def');
insert into items values (602, 'X Defense');
insert into items values (603, 'X Attack');
insert into items values (604, 'X Accuracy');
insert into items values (605, 'X Speed');
insert into items values (606, 'X Sp. Atk');
insert into items values (607, 'X Sp. Def');
insert into items values (608, 'X Defense');
insert into items values (609, 'X Attack');
insert into items values (610, 'X Accuracy');
insert into items values (611, 'Ability Urge');
insert into items values (612, 'Item Drop');
insert into items values (613, 'Item Urge');
insert into items values (614, 'Reset Urge');
insert into items values (615, 'Dire Hit');
insert into items values (616, 'Light Stone');
insert into items values (617, 'Dark Stone');
insert into items values (618, 'TM Normal');
insert into items values (619, 'TM Normal');
insert into items values (620, 'TM Normal');
insert into items values (621, 'Xtransceiver Male');
insert into items values (622, 'God Stone');
insert into items values (623, 'Gram');
insert into items values (624, 'Gram');
insert into items values (625, 'Gram');
insert into items values (626, 'Xtransceiver Female');
insert into items values (627, 'Medal Box');
insert into items values (628, 'DNA Splicers');
insert into items values (629, 'DNA Splicers');
insert into items values (630, 'Permit');
insert into items values (631, 'Oval Charm');
insert into items values (632, 'Shiny Charm');
insert into items values (633, 'Plasma Card');
insert into items values (634, 'Grubby Hanky');
insert into items values (635, 'Colress Machine');
insert into items values (636, 'Dropped Item Male');
insert into items values (637, 'Dropped Item Female');
insert into items values (638, 'Reveal Glass');
insert into items values (639, 'Weakness Policy');
insert into items values (640, 'Assault Vest');
insert into items values (641, 'Holo Caster Male');
insert into items values (642, 'Prof''s Letter');
insert into items values (643, 'Roller Skates');
insert into items values (644, 'Pixie Plate');
insert into items values (645, 'Ability Capsule');
insert into items values (646, 'Whipped Dream');
insert into items values (647, 'Sachet');
insert into items values (648, 'Luminous Moss');
insert into items values (649, 'Snowball');
insert into items values (650, 'Safety Goggles');
insert into items values (651, 'Poké Flute');
insert into items values (652, 'Rich Mulch');
insert into items values (653, 'Surprise Mulch');
insert into items values (654, 'Boost Mulch');
insert into items values (655, 'Amaze Mulch');
insert into items values (656, 'Gengarite');
insert into items values (657, 'Gardevoirite');
insert into items values (658, 'Ampharosite');
insert into items values (659, 'Venusaurite');
insert into items values (660, 'Charizardite X');
insert into items values (661, 'Blastoisinite');
insert into items values (662, 'Mewtwonite X');
insert into items values (663, 'Mewtwonite Y');
insert into items values (664, 'Blazikenite');
insert into items values (665, 'Medichamite');
insert into items values (666, 'Houndoominite');
insert into items values (667, 'Aggronite');
insert into items values (668, 'Banettite');
insert into items values (669, 'Tyranitarite');
insert into items values (670, 'Scizorite');
insert into items values (671, 'Pinsirite');
insert into items values (672, 'Aerodactylite');
insert into items values (673, 'Lucarionite');
insert into items values (674, 'Abomasite');
insert into items values (675, 'Kangaskhanite');
insert into items values (676, 'Gyaradosite');
insert into items values (677, 'Absolite');
insert into items values (678, 'Charizardite Y');
insert into items values (679, 'Alakazite');
insert into items values (680, 'Heracronite');
insert into items values (681, 'Mawilite');
insert into items values (682, 'Manectite');
insert into items values (683, 'Garchompite');
insert into items values (684, 'Latiasite');
insert into items values (685, 'Latiosite');
insert into items values (686, 'Roseli Berry');
insert into items values (687, 'Kee Berry');
insert into items values (688, 'Maranga Berry');
insert into items values (689, 'Sprinklotad');
insert into items values (690, 'TM Normal');
insert into items values (691, 'TM Normal');
insert into items values (692, 'TM Normal');
insert into items values (693, 'TM Normal');
insert into items values (694, 'TM Normal');
insert into items values (695, 'Power Plant Pass');
insert into items values (696, 'Mega Ring');
insert into items values (697, 'Intriguing Stone');
insert into items values (698, 'Common Stone');
insert into items values (699, 'Discount Coupon');
insert into items values (700, 'Elevator Key');
insert into items values (701, 'TMV Pass');
insert into items values (702, 'Honor of Kalos');
insert into items values (703, 'Adventure Guide');
insert into items values (704, 'Strange Souvenir');
insert into items values (705, 'Lens Case');
insert into items values (706, 'Makeup Bag');
insert into items values (707, 'Travel Trunk');
insert into items values (708, 'Lumiose Galette');
insert into items values (709, 'Shalour Sable');
insert into items values (710, 'Jaw Fossil');
insert into items values (711, 'Sail Fossil');
insert into items values (712, 'Looker Ticket');
insert into items values (713, 'Bike');
insert into items values (714, 'Holo Caster Female');
insert into items values (715, 'Fairy Gem');
insert into items values (716, 'Mega Charm');
insert into items values (717, 'Mega Glove');
insert into items values (718, 'Mach Bike');
insert into items values (719, 'Acro Bike');
insert into items values (720, 'Wailmer Pail');
insert into items values (721, 'Devon Parts');
insert into items values (722, 'Soot Sack');
insert into items values (723, 'Basement Key');
insert into items values (724, 'Pokéblock Kit');
insert into items values (725, 'Letter');
insert into items values (726, 'Eon Ticket');
insert into items values (727, 'Scanner');
insert into items values (728, 'Go-Goggles');
insert into items values (729, 'Meteorite');
insert into items values (730, 'Key 1');
insert into items values (731, 'Key 2');
insert into items values (732, 'Key 4');
insert into items values (733, 'Key 6');
insert into items values (734, 'Storage Key');
insert into items values (735, 'Devon Scope');
insert into items values (736, 'S.S. Ticket');
insert into items values (737, 'TM Normal');
insert into items values (738, 'Devon Scuba Gear');
insert into items values (739, 'Contest Costume Male');
insert into items values (740, 'Contest Costume Female');
insert into items values (741, 'Magma Suit');
insert into items values (742, 'Aqua Suit');
insert into items values (743, 'Pair of Tickets');
insert into items values (744, 'Mega Bracelet');
insert into items values (745, 'Mega Pendant');
insert into items values (746, 'Mega Glasses');
insert into items values (747, 'Mega Anchor');
insert into items values (748, 'Mega Stickpin');
insert into items values (749, 'Mega Tiara');
insert into items values (750, 'Mega Anklet');
insert into items values (751, 'Meteorite');
insert into items values (752, 'Swampertite');
insert into items values (753, 'Sceptilite');
insert into items values (754, 'Sablenite');
insert into items values (755, 'Alatarianite');
insert into items values (756, 'Galladite');
insert into items values (757, 'Audinite');
insert into items values (758, 'Metagrossite');
insert into items values (759, 'Sharpedonite');
insert into items values (760, 'Slowbronite');
insert into items values (761, 'Steelixite');
insert into items values (762, 'Pidgeotite');
insert into items values (763, 'Glalitite');
insert into items values (764, 'Diancite');
insert into items values (765, 'Prison Bottle');
insert into items values (766, 'Mega Cuff');
insert into items values (767, 'Cameruptite');
insert into items values (768, 'Lopunnite');
insert into items values (769, 'Salamencite');
insert into items values (770, 'Beedrillite');
insert into items values (771, 'Meteorite');
insert into items values (772, 'Meteorite');
insert into items values (773, 'Key Stone');
insert into items values (774, 'Meteorite Shard');
insert into items values (775, 'Eon Flute');
insert into items values (776, 'Normalium Z');
insert into items values (777, 'Firium Z');
insert into items values (778, 'Waterium Z');
insert into items values (779, 'Electrium Z');
insert into items values (780, 'Grassium Z');
insert into items values (781, 'Icium Z');
insert into items values (782, 'Fightinium Z');
insert into items values (783, 'Poisonium Z');
insert into items values (784, 'Groundium Z');
insert into items values (785, 'Flyinium Z');
insert into items values (786, 'Psychium Z');
insert into items values (787, 'Buginium Z');
insert into items values (788, 'Rockium Z');
insert into items values (789, 'Ghostium Z');
insert into items values (790, 'Dragonium Z');
insert into items values (791, 'Darkinium Z');
insert into items values (792, 'Steelium Z');
insert into items values (793, 'Fairium Z');
insert into items values (794, 'Pikanium Z');
insert into items values (795, 'Bottle Cap');
insert into items values (796, 'Gold Bottle Cap');
insert into items values (797, 'Z-Ring');
insert into items values (798, 'Decidium Z');
insert into items values (799, 'Incinium Z');
insert into items values (800, 'Primarium Z');
insert into items values (801, 'Tapunium Z');
insert into items values (802, 'Marshadium Z');
insert into items values (803, 'Aloraichium Z');
insert into items values (804, 'Snorlium Z');
insert into items values (805, 'Eevium Z');
insert into items values (806, 'Mewnium Z');
insert into items values (807, 'Normalium Z');
insert into items values (808, 'Firium Z');
insert into items values (809, 'Waterium Z');
insert into items values (810, 'Electrium Z');
insert into items values (811, 'Grassium Z');
insert into items values (812, 'Icium Z');
insert into items values (813, 'Fightinium Z');
insert into items values (814, 'Poisonium Z');
insert into items values (815, 'Groundium Z');
insert into items values (816, 'Flyinium Z');
insert into items values (817, 'Psychium Z');
insert into items values (818, 'Buginium Z');
insert into items values (819, 'Rockium Z');
insert into items values (820, 'Ghostium Z');
insert into items values (821, 'Dragonium Z');
insert into items values (822, 'Darkinium Z');
insert into items values (823, 'Steelium Z');
insert into items values (824, 'Fairium Z');
insert into items values (825, 'Pikanium Z');
insert into items values (826, 'Decidium Z');
insert into items values (827, 'Icinium Z');
insert into items values (828, 'Primarium Z');
insert into items values (829, 'Tapunium Z');
insert into items values (830, 'Marshadium Z');
insert into items values (831, 'Aloraichium Z');
insert into items values (832, 'Snorlium Z');
insert into items values (833, 'Eevium Z');
insert into items values (834, 'Mewnium Z');
insert into items values (835, 'Pikashunium Z');
insert into items values (836, 'Pikashunium Z');
insert into items values (837, 'Unknown');
insert into items values (838, 'Unknown');
insert into items values (839, 'Unknown');
insert into items values (840, 'Unknown');
insert into items values (841, 'Forage Bag');
insert into items values (842, 'Fishing Rod');
insert into items values (843, 'Professor''s Mask');
insert into items values (844, 'Festival Ticket');
insert into items values (845, 'Sparkling Stone');
insert into items values (846, 'Adrenaline Orb');
insert into items values (847, 'Zygarde Cube');
insert into items values (848, 'Unknown');
insert into items values (849, 'Ice Stone');
insert into items values (850, 'Ride Pager');
insert into items values (851, 'Beast Ball');
insert into items values (852, 'Big Malasada');
insert into items values (853, 'Red Nectar');
insert into items values (854, 'Yellow Nectar');
insert into items values (855, 'Pink Nectar');
insert into items values (856, 'Purple Nectar');
insert into items values (857, 'Sun Flute');
insert into items values (858, 'Moon Flute');
insert into items values (859, 'Unknown');
insert into items values (860, 'Enigmatic Card');
insert into items values (861, 'Silver Razz Berry');
insert into items values (862, 'Golden Razz Berry');
insert into items values (863, 'Silver Nanab Berry');
insert into items values (864, 'Golden Nanab Berry');
insert into items values (865, 'Silver Pinap Berry');
insert into items values (866, 'Golden Pinap Berry');
insert into items values (867, 'Unknown');
insert into items values (868, 'Unknown');
insert into items values (869, 'Unknown');
insert into items values (870, 'Unknown');
insert into items values (871, 'Unknown');
insert into items values (872, 'Secret Key');
insert into items values (873, 'S.S. Ticket');
insert into items values (874, 'Silph Scope');
insert into items values (875, 'Parcel');
insert into items values (876, 'Card Key');
insert into items values (877, 'Gold Teeth');
insert into items values (878, 'Lift Key');
insert into items values (879, 'Terrain Extender');
insert into items values (880, 'Protective Pads');
insert into items values (881, 'Electric Seed');
insert into items values (882, 'Psychic Seed');
insert into items values (883, 'Misty Seed');
insert into items values (884, 'Grassy Seed');
insert into items values (885, 'Stetchy Spring');
insert into items values (886, 'Chalky Stone');
insert into items values (887, 'Marble');
insert into items values (888, 'Lone Earring');
insert into items values (889, 'Beach Glass');
insert into items values (890, 'Gold Leaf');
insert into items values (891, 'Silver Leaf');
insert into items values (892, 'Polished Mud Ball');
insert into items values (893, 'Tropical Shell');
insert into items values (894, 'Leaf Letter');
insert into items values (895, 'Leaf Letter');
insert into items values (896, 'Small Bouquet');
insert into items values (897, 'Unknown');
insert into items values (898, 'Unknown');
insert into items values (899, 'Unknown');
insert into items values (900, 'Lure');
insert into items values (901, 'Super Lure');
insert into items values (902, 'Max Lure');
insert into items values (903, 'Pewter Crunchies');
insert into items values (904, 'Fighting Memory');
insert into items values (905, 'Flying Memory');
insert into items values (906, 'Poison Memory');
insert into items values (907, 'Ground Memory');
insert into items values (908, 'Rock Memory');
insert into items values (909, 'Bug Memory');
insert into items values (910, 'Ghost Memory');
insert into items values (911, 'Steel Memory');
insert into items values (912, 'Fire Memory');
insert into items values (913, 'Water Memory');
insert into items values (914, 'Grass Memory');
insert into items values (915, 'Electric Memory');
insert into items values (916, 'Psychic Memory');
insert into items values (917, 'Ice Memory');
insert into items values (918, 'Dragon Memory');
insert into items values (919, 'Dark Memory');
insert into items values (920, 'Fairy Memory');
insert into items values (921, 'Solganium Z');
insert into items values (922, 'Lunalium');
insert into items values (923, 'Ultranecrozium');
insert into items values (924, 'Mimikium');
insert into items values (925, 'Lycanium Z');
insert into items values (926, 'Kommonium Z');
insert into items values (927, 'Solganium Z');
insert into items values (928, 'Lunalium Z');
insert into items values (929, 'Ultranecrozium Z');
insert into items values (930, 'Mimikium Z');
insert into items values (931, 'Lycanium Z');
insert into items values (932, 'Kommonium Z');
insert into items values (933, 'Z-Power Ring');
insert into items values (934, 'Pink Petal');
insert into items values (935, 'Orange Petal');
insert into items values (936, 'Blue Petal');
insert into items values (937, 'Red Petal');
insert into items values (938, 'Green Petal');
insert into items values (939, 'Yellow Petal');
insert into items values (940, 'Purple Petal');
insert into items values (941, 'Rainbow Flower');
insert into items values (942, 'Surge Badge');
insert into items values (943, 'N-Solarizer');
insert into items values (944, 'N-Lunarizer');
insert into items values (945, 'N-Solarizer');
insert into items values (946, 'N-Lunarizer');
insert into items values (947, 'Normalium Z');
insert into items values (948, 'Poké Ball');
insert into items values (949, 'Roto Hatch');
insert into items values (950, 'Roto Bargain');
insert into items values (951, 'Roto Prize Money');
insert into items values (952, 'Roto Exp. Points');
insert into items values (953, 'Roto Friendship');
insert into items values (954, 'Roto Encounter');
insert into items values (955, 'Roto Stealth');
insert into items values (956, 'Roto HP Restore');
insert into items values (957, 'Roto PP Restore');
insert into items values (958, 'Roto Boost');
insert into items values (959, 'Roto Catch');
insert into items values (960, 'Health Candy');
insert into items values (961, 'Mighty Candy');
insert into items values (962, 'Tough Candy');
insert into items values (963, 'Smart Candy');
insert into items values (964, 'Courage Candy');
insert into items values (965, 'Quick Candy');
insert into items values (966, 'Health Candy L');
insert into items values (967, 'Mighty Candy L');
insert into items values (968, 'Tough Candy L');
insert into items values (969, 'Smart Candy L');
insert into items values (970, 'Courage Candy L');
insert into items values (971, 'Quick Candy L');
insert into items values (972, 'Health Candy XL');
insert into items values (973, 'Mighty Candy XL');
insert into items values (974, 'Tough Candy XL');
insert into items values (975, 'Smart Candy XL');
insert into items values (976, 'Courage Candy XL');
insert into items values (977, 'Quick Candy XL');
insert into items values (978, 'Candy Green');
insert into items values (979, 'Candy Red');
insert into items values (980, 'Candy Blue');
insert into items values (981, 'Candy Green');
insert into items values (982, 'Candy Brown');
insert into items values (983, 'Candy Brown');
insert into items values (984, 'Candy Purple');
insert into items values (985, 'Candy Brown');
insert into items values (986, 'Candy Purple');
insert into items values (987, 'Candy Yellow');
insert into items values (988, 'Candy Yellow');
insert into items values (989, 'Candy Blue');
insert into items values (990, 'Candy Purple');
insert into items values (991, 'Candy Pink');
insert into items values (992, 'Candy Brown');
insert into items values (993, 'Candy Pink');
insert into items values (994, 'Candy Purple');
insert into items values (995, 'Candy Blue');
insert into items values (996, 'Candy Red');
insert into items values (997, 'Candy Purple');
insert into items values (998, 'Candy Brown');
insert into items values (999, 'Candy Yellow');
insert into items values (1000, 'Candy Yellow');
insert into items values (1001, 'Candy Brown');
insert into items values (1002, 'Candy Brown');
insert into items values (1003, 'Candy Blue');
insert into items values (1004, 'Candy Brown');
insert into items values (1005, 'Candy Gray');
insert into items values (1006, 'Candy Green');
insert into items values (1007, 'Candy Blue');
insert into items values (1008, 'Candy Brown');
insert into items values (1009, 'Candy Candy Yellow');
insert into items values (1010, 'Candy Pink');
insert into items values (1011, 'Candy Gray');
insert into items values (1012, 'Candy Brown');
insert into items values (1013, 'Candy Brown');
insert into items values (1014, 'Candy White');
insert into items values (1015, 'Candy Purple');
insert into items values (1016, 'Candy Purple');
insert into items values (1017, 'Candy Purple');
insert into items values (1018, 'Candy Gray');
insert into items values (1019, 'Candy Yellow');
insert into items values (1020, 'Candy Red');
insert into items values (1021, 'Candy Red');
insert into items values (1022, 'Candy Pink');
insert into items values (1023, 'Candy Brown');
insert into items values (1024, 'Candy Brown');
insert into items values (1025, 'Candy Brown');
insert into items values (1026, 'Candy Pink');
insert into items values (1027, 'Candy Purple');
insert into items values (1028, 'Candy Gray');
insert into items values (1029, 'Candy Pink');
insert into items values (1030, 'Candy Blue');
insert into items values (1031, 'Candy Brown');
insert into items values (1032, 'Candy Blue');
insert into items values (1033, 'Candy Red');
insert into items values (1034, 'Candy Brown');
insert into items values (1035, 'Candy Pink');
insert into items values (1036, 'Candy Green');
insert into items values (1037, 'Candy Red');
insert into items values (1038, 'Candy Yellow');
insert into items values (1039, 'Candy Red');
insert into items values (1040, 'Candy Brown');
insert into items values (1041, 'Candy Brown');
insert into items values (1042, 'Candy Red');
insert into items values (1043, 'Candy Blue');
insert into items values (1044, 'Candy Purple');
insert into items values (1045, 'Candy Brown');
insert into items values (1046, 'Candy Pink');
insert into items values (1047, 'Candy Blue');
insert into items values (1048, 'Candy Brown');
insert into items values (1049, 'Candy Purple');
insert into items values (1050, 'Candy Black');
insert into items values (1051, 'Candy Blue');
insert into items values (1052, 'Candy Yellow');
insert into items values (1053, 'Candy Yellow');
insert into items values (1054, 'Candy Blue');
insert into items values (1055, 'Candy Purple');
insert into items values (1056, 'Candy Pink');
insert into items values (1057, 'Candy Gray');
insert into items values (1058, 'Unknown');
insert into items values (1059, 'Unknown');
insert into items values (1060, 'Unknown');
insert into items values (1061, 'Unknown');
insert into items values (1062, 'Unknown');
insert into items values (1063, 'Unknown');
insert into items values (1064, 'Unknown');
insert into items values (1065, 'Unknown');
insert into items values (1066, 'Unknown');
insert into items values (1067, 'Unknown');
insert into items values (1068, 'Unknown');
insert into items values (1069, 'Unknown');
insert into items values (1070, 'Unknown');
insert into items values (1071, 'Unknown');
insert into items values (1072, 'Unknown');
insert into items values (1073, 'Unknown');
insert into items values (1074, 'Endorsement');
insert into items values (1075, 'Pokémon Box Link');
insert into items values (1076, 'Wishing Star');
insert into items values (1077, 'Dynamax Band');
insert into items values (1078, 'Unknown');
insert into items values (1079, 'Unknown');
insert into items values (1080, 'Fishing Rod');
insert into items values (1081, 'Rotom Bike');
insert into items values (1082, 'Unknown');
insert into items values (1083, 'Unknown');
insert into items values (1084, 'Sausages');
insert into items values (1085, 'Bob''s Food Tin');
insert into items values (1086, 'Bach''s Food Tin');
insert into items values (1087, 'Tin of Beans');
insert into items values (1088, 'Bread');
insert into items values (1089, 'Pasta');
insert into items values (1090, 'Mixed Mushrooms');
insert into items values (1091, 'Smoke-Poke Tail');
insert into items values (1092, 'Large Leek');
insert into items values (1093, 'Fancy Apple');
insert into items values (1094, 'Brittle Bones');
insert into items values (1095, 'Pack of Potatoes');
insert into items values (1096, 'Pungent Root');
insert into items values (1097, 'Salad Mix');
insert into items values (1098, 'Fried Food');
insert into items values (1099, 'Boiled Egg');
insert into items values (1100, 'Camping Gear');
insert into items values (1101, 'Unknown');
insert into items values (1102, 'Unknown');
insert into items values (1103, 'Rusted Sword');
insert into items values (1104, 'Rusted Shield');
insert into items values (1105, 'Fossilized Bird');
insert into items values (1106, 'Fossilized Fish');
insert into items values (1107, 'Fossilized Drake');
insert into items values (1108, 'Fossilized Dino');
insert into items values (1109, 'Strawberry Sweet');
insert into items values (1110, 'Love Sweet');
insert into items values (1111, 'Berry Sweet');
insert into items values (1112, 'Clover Sweet');
insert into items values (1113, 'Flower Sweet');
insert into items values (1114, 'Star Sweet');
insert into items values (1115, 'Ribbon Sweet');
insert into items values (1116, 'Sweet Apple');
insert into items values (1117, 'Tart Apple');
insert into items values (1118, 'Throat Spray');
insert into items values (1119, 'Eject Pack');
insert into items values (1120, 'Heavy-Duty Boots');
insert into items values (1121, 'Blunder Policy');
insert into items values (1122, 'Room Service');
insert into items values (1123, 'Utility Umbrella');
insert into items values (1124, 'Exp. Candy XS');
insert into items values (1125, 'Exp. Candy S');
insert into items values (1126, 'Exp. Candy M');
insert into items values (1127, 'Exp. Candy L');
insert into items values (1128, 'Exp. Candy XL');
insert into items values (1129, 'Dynamax Candy');
insert into items values (1130, 'TM Normal');
insert into items values (1131, 'TM Normal');
insert into items values (1132, 'TM Normal');
insert into items values (1133, 'TM Normal');
insert into items values (1134, 'TM Normal');
insert into items values (1135, 'TM Normal');
insert into items values (1136, 'TM Normal');
insert into items values (1137, 'TM Normal');
insert into items values (1138, 'TM Normal');
insert into items values (1139, 'TM Normal');
insert into items values (1140, 'TM Normal');
insert into items values (1141, 'TM Normal');
insert into items values (1142, 'TM Normal');
insert into items values (1143, 'TM Normal');
insert into items values (1144, 'TM Normal');
insert into items values (1145, 'TM Normal');
insert into items values (1146, 'TM Normal');
insert into items values (1147, 'TM Normal');
insert into items values (1148, 'TM Normal');
insert into items values (1149, 'TM Normal');
insert into items values (1150, 'TM Normal');
insert into items values (1151, 'TM Normal');
insert into items values (1152, 'TM Normal');
insert into items values (1153, 'TM Normal');
insert into items values (1154, 'TM Normal');
insert into items values (1155, 'TM Normal');
insert into items values (1156, 'TM Normal');
insert into items values (1157, 'TM Normal');
insert into items values (1158, 'TM Normal');
insert into items values (1159, 'TM Normal');
insert into items values (1160, 'TM Normal');
insert into items values (1161, 'TM Normal');
insert into items values (1162, 'TM Normal');
insert into items values (1163, 'TM Normal');
insert into items values (1164, 'TM Normal');
insert into items values (1165, 'TM Normal');
insert into items values (1166, 'TM Normal');
insert into items values (1167, 'TM Normal');
insert into items values (1168, 'TM Normal');
insert into items values (1169, 'TM Normal');
insert into items values (1170, 'TM Normal');
insert into items values (1171, 'TM Normal');
insert into items values (1172, 'TM Normal');
insert into items values (1173, 'TM Normal');
insert into items values (1174, 'TM Normal');
insert into items values (1175, 'TM Normal');
insert into items values (1176, 'TM Normal');
insert into items values (1177, 'TM Normal');
insert into items values (1178, 'TM Normal');
insert into items values (1179, 'TM Normal');
insert into items values (1180, 'TM Normal');
insert into items values (1181, 'TM Normal');
insert into items values (1182, 'TM Normal');
insert into items values (1183, 'TM Normal');
insert into items values (1184, 'TM Normal');
insert into items values (1185, 'TM Normal');
insert into items values (1186, 'TM Normal');
insert into items values (1187, 'TM Normal');
insert into items values (1188, 'TM Normal');
insert into items values (1189, 'TM Normal');
insert into items values (1190, 'TM Normal');
insert into items values (1191, 'TM Normal');
insert into items values (1192, 'TM Normal');
insert into items values (1193, 'TM Normal');
insert into items values (1194, 'TM Normal');
insert into items values (1195, 'TM Normal');
insert into items values (1196, 'TM Normal');
insert into items values (1197, 'TM Normal');
insert into items values (1198, 'TM Normal');
insert into items values (1199, 'TM Normal');
insert into items values (1200, 'TM Normal');
insert into items values (1201, 'TM Normal');
insert into items values (1202, 'TM Normal');
insert into items values (1203, 'TM Normal');
insert into items values (1204, 'TM Normal');
insert into items values (1205, 'TM Normal');
insert into items values (1206, 'TM Normal');
insert into items values (1207, 'TM Normal');
insert into items values (1208, 'TM Normal');
insert into items values (1209, 'TM Normal');
insert into items values (1210, 'TM Normal');
insert into items values (1211, 'TM Normal');
insert into items values (1212, 'TM Normal');
insert into items values (1213, 'TM Normal');
insert into items values (1214, 'TM Normal');
insert into items values (1215, 'TM Normal');
insert into items values (1216, 'TM Normal');
insert into items values (1217, 'TM Normal');
insert into items values (1218, 'TM Normal');
insert into items values (1219, 'TM Normal');
insert into items values (1220, 'TM Normal');
insert into items values (1221, 'TM Normal');
insert into items values (1222, 'TM Normal');
insert into items values (1223, 'TM Normal');
insert into items values (1224, 'TM Normal');
insert into items values (1225, 'TM Normal');
insert into items values (1226, 'TM Normal');
insert into items values (1227, 'TM Normal');
insert into items values (1228, 'TM Normal');
insert into items values (1229, 'TM Normal');
insert into items values (1230, 'TM Normal');
insert into items values (1231, 'Red Mint');
insert into items values (1232, 'Red Mint');
insert into items values (1233, 'Red Mint');
insert into items values (1234, 'Red Mint');
insert into items values (1235, 'Blue Mint');
insert into items values (1236, 'Blue Mint');
insert into items values (1237, 'Blue Mint');
insert into items values (1238, 'Blue Mint');
insert into items values (1239, 'Cyan Mint');
insert into items values (1240, 'Cyan Mint');
insert into items values (1241, 'Cyan Mint');
insert into items values (1242, 'Cyan Mint');
insert into items values (1243, 'Pink Mint');
insert into items values (1244, 'Pink Mint');
insert into items values (1245, 'Pink Mint');
insert into items values (1246, 'Pink Mint');
insert into items values (1247, 'Green Mint');
insert into items values (1248, 'Green Mint');
insert into items values (1249, 'Green Mint');
insert into items values (1250, 'Green Mint');
insert into items values (1251, 'Yellow Mint');
insert into items values (1252, 'Wishing Piece');
insert into items values (1253, 'Cracked Pot');
insert into items values (1254, 'Chipped Pot');
insert into items values (1255, 'Hi-tech Earbuds');
insert into items values (1256, 'Fruit Bunch');
insert into items values (1257, 'Moomoo Cheese');
insert into items values (1258, 'Spice Mix');
insert into items values (1259, 'Fresh Cream');
insert into items values (1260, 'Packaged Curry');
insert into items values (1261, 'Coconut Milk');
insert into items values (1262, 'Instant Noodles');
insert into items values (1263, 'Precooked Burger');
insert into items values (1264, 'Gigantamix');
insert into items values (1265, 'Wishing Chip');
insert into items values (1266, 'Rotom Bike');
insert into items values (1267, 'Catching Charm');
insert into items values (1268, 'Unknown');
insert into items values (1269, 'Old Letter');
insert into items values (1270, 'Band Autograph');
insert into items values (1271, 'Sonia''s Book');
insert into items values (1272, 'Unknown');
insert into items values (1273, 'Unknown');
insert into items values (1274, 'Unknown');
insert into items values (1275, 'Unknown');
insert into items values (1276, 'Unknown');
insert into items values (1277, 'Unknown');
insert into items values (1278, 'Rotom Catalog');
insert into items values (1279, 'Dynamax Crystal');
insert into items values (1280, 'Dynamax Crystal');
insert into items values (1281, 'Dynamax Crystal');
insert into items values (1282, 'Dynamax Crystal');
insert into items values (1283, 'Dynamax Crystal');
insert into items values (1284, 'Dynamax Crystal');
insert into items values (1285, 'Dynamax Crystal');
insert into items values (1286, 'Dynamax Crystal');
insert into items values (1287, 'Dynamax Crystal');
insert into items values (1288, 'Dynamax Crystal');
insert into items values (1289, 'Dynamax Crystal');
insert into items values (1290, 'Dynamax Crystal');
insert into items values (1291, 'Dynamax Crystal');
insert into items values (1292, 'Dynamax Crystal');
insert into items values (1293, 'Dynamax Crystal');
insert into items values (1294, 'Dynamax Crystal');
insert into items values (1295, 'Dynamax Crystal');
insert into items values (1296, 'Dynamax Crystal');
insert into items values (1297, 'Dynamax Crystal');
insert into items values (1298, 'Dynamax Crystal');
insert into items values (1299, 'Dynamax Crystal');
insert into items values (1300, 'Dynamax Crystal');
insert into items values (1301, 'Dynamax Crystal');
insert into items values (1302, 'Dynamax Crystal');
insert into items values (1303, 'Dynamax Crystal');
insert into items values (1304, 'Dynamax Crystal');
insert into items values (1305, 'Dynamax Crystal');
insert into items values (1306, 'Dynamax Crystal');
insert into items values (1307, 'Dynamax Crystal');
insert into items values (1308, 'Dynamax Crystal');
insert into items values (1309, 'Dynamax Crystal');
insert into items values (1310, 'Dynamax Crystal');
insert into items values (1311, 'Dynamax Crystal');
insert into items values (1312, 'Dynamax Crystal');
insert into items values (1313, 'Dynamax Crystal');
insert into items values (1314, 'Dynamax Crystal');
insert into items values (1315, 'Dynamax Crystal');
insert into items values (1316, 'Dynamax Crystal');
insert into items values (1317, 'Dynamax Crystal');
insert into items values (1318, 'Dynamax Crystal');
insert into items values (1319, 'Dynamax Crystal');
insert into items values (1320, 'Dynamax Crystal');
insert into items values (1321, 'Dynamax Crystal');
insert into items values (1322, 'Dynamax Crystal');
insert into items values (1323, 'Dynamax Crystal');
insert into items values (1324, 'Dynamax Crystal');
insert into items values (1325, 'Dynamax Crystal');
insert into items values (1326, 'Dynamax Crystal');
insert into items values (1327, 'Dynamax Crystal');
insert into items values (1328, 'Dynamax Crystal');
insert into items values (1329, 'Dynamax Crystal');
insert into items values (1330, 'Dynamax Crystal');
insert into items values (1331, 'Dynamax Crystal');
insert into items values (1332, 'Dynamax Crystal');
insert into items values (1333, 'Dynamax Crystal');
insert into items values (1334, 'Dynamax Crystal');
insert into items values (1335, 'Dynamax Crystal');
insert into items values (1336, 'Dynamax Crystal');
insert into items values (1337, 'Dynamax Crystal');
insert into items values (1338, 'Dynamax Crystal');
insert into items values (1339, 'Dynamax Crystal');
insert into items values (1340, 'Dynamax Crystal');
insert into items values (1341, 'Dynamax Crystal');
insert into items values (1342, 'Dynamax Crystal');
insert into items values (1343, 'Dynamax Crystal');
insert into items values (1344, 'Dynamax Crystal');
insert into items values (1345, 'Dynamax Crystal');
insert into items values (1346, 'Dynamax Crystal');
insert into items values (1347, 'Dynamax Crystal');
insert into items values (1348, 'Dynamax Crystal');
insert into items values (1349, 'Dynamax Crystal');
insert into items values (1350, 'Dynamax Crystal');
insert into items values (1351, 'Dynamax Crystal');
insert into items values (1352, 'Dynamax Crystal');
insert into items values (1353, 'Dynamax Crystal');
insert into items values (1354, 'Dynamax Crystal');
insert into items values (1355, 'Dynamax Crystal');
insert into items values (1356, 'Dynamax Crystal');
insert into items values (1357, 'Dynamax Crystal');
insert into items values (1358, 'Dynamax Crystal');
insert into items values (1359, 'Dynamax Crystal');
insert into items values (1360, 'Dynamax Crystal');
insert into items values (1361, 'Dynamax Crystal');
insert into items values (1362, 'Dynamax Crystal');
insert into items values (1363, 'Dynamax Crystal');
insert into items values (1364, 'Dynamax Crystal');
insert into items values (1365, 'Dynamax Crystal');
insert into items values (1366, 'Dynamax Crystal');
insert into items values (1367, 'Dynamax Crystal');
insert into items values (1368, 'Dynamax Crystal');
insert into items values (1369, 'Dynamax Crystal');
insert into items values (1370, 'Dynamax Crystal');
insert into items values (1371, 'Dynamax Crystal');
insert into items values (1372, 'Dynamax Crystal');
insert into items values (1373, 'Dynamax Crystal');
insert into items values (1374, 'Dynamax Crystal');
insert into items values (1375, 'Dynamax Crystal');
insert into items values (1376, 'Dynamax Crystal');
insert into items values (1377, 'Dynamax Crystal');
insert into items values (1378, 'Dynamax Crystal');
insert into items values (1379, 'Dynamax Crystal');
insert into items values (1380, 'Dynamax Crystal');
insert into items values (1381, 'Dynamax Crystal');
insert into items values (1382, 'Dynamax Crystal');
insert into items values (1383, 'Dynamax Crystal');
insert into items values (1384, 'Dynamax Crystal');
insert into items values (1385, 'Dynamax Crystal');
insert into items values (1386, 'Dynamax Crystal');
insert into items values (1387, 'Dynamax Crystal');
insert into items values (1388, 'Dynamax Crystal');
insert into items values (1389, 'Dynamax Crystal');
insert into items values (1390, 'Dynamax Crystal');
insert into items values (1391, 'Dynamax Crystal');
insert into items values (1392, 'Dynamax Crystal');
insert into items values (1393, 'Dynamax Crystal');
insert into items values (1394, 'Dynamax Crystal');
insert into items values (1395, 'Dynamax Crystal');
insert into items values (1396, 'Dynamax Crystal');
insert into items values (1397, 'Dynamax Crystal');
insert into items values (1398, 'Dynamax Crystal');
insert into items values (1399, 'Dynamax Crystal');
insert into items values (1400, 'Dynamax Crystal');
insert into items values (1401, 'Dynamax Crystal');
insert into items values (1402, 'Dynamax Crystal');
insert into items values (1403, 'Dynamax Crystal');
insert into items values (1404, 'Dynamax Crystal');
insert into items values (1405, 'Dynamax Crystal');
insert into items values (1406, 'Dynamax Crystal');
insert into items values (1407, 'Dynamax Crystal');
insert into items values (1408, 'Dynamax Crystal');
insert into items values (1409, 'Dynamax Crystal');
insert into items values (1410, 'Dynamax Crystal');
insert into items values (1411, 'Dynamax Crystal');
insert into items values (1412, 'Dynamax Crystal');
insert into items values (1413, 'Dynamax Crystal');
insert into items values (1414, 'Dynamax Crystal');
insert into items values (1415, 'Dynamax Crystal');
insert into items values (1416, 'Dynamax Crystal');
insert into items values (1417, 'Dynamax Crystal');
insert into items values (1418, 'Dynamax Crystal');
insert into items values (1419, 'Dynamax Crystal');
insert into items values (1420, 'Dynamax Crystal');
insert into items values (1421, 'Dynamax Crystal');
insert into items values (1422, 'Dynamax Crystal');
insert into items values (1423, 'Dynamax Crystal');
insert into items values (1424, 'Dynamax Crystal');
insert into items values (1425, 'Dynamax Crystal');
insert into items values (1426, 'Dynamax Crystal');
insert into items values (1427, 'Dynamax Crystal');
insert into items values (1428, 'Dynamax Crystal');
insert into items values (1429, 'Dynamax Crystal');
insert into items values (1430, 'Dynamax Crystal');
insert into items values (1431, 'Dynamax Crystal');
insert into items values (1432, 'Dynamax Crystal');
insert into items values (1433, 'Dynamax Crystal');
insert into items values (1434, 'Dynamax Crystal');
insert into items values (1435, 'Dynamax Crystal');
insert into items values (1436, 'Dynamax Crystal');
insert into items values (1437, 'Dynamax Crystal');
insert into items values (1438, 'Dynamax Crystal');
insert into items values (1439, 'Dynamax Crystal');
insert into items values (1440, 'Dynamax Crystal');
insert into items values (1441, 'Dynamax Crystal');
insert into items values (1442, 'Dynamax Crystal');
insert into items values (1443, 'Dynamax Crystal');
insert into items values (1444, 'Dynamax Crystal');
insert into items values (1445, 'Dynamax Crystal');
insert into items values (1446, 'Dynamax Crystal');
insert into items values (1447, 'Dynamax Crystal');
insert into items values (1448, 'Dynamax Crystal');
insert into items values (1449, 'Dynamax Crystal');
insert into items values (1450, 'Dynamax Crystal');
insert into items values (1451, 'Dynamax Crystal');
insert into items values (1452, 'Dynamax Crystal');
insert into items values (1453, 'Dynamax Crystal');
insert into items values (1454, 'Dynamax Crystal');
insert into items values (1455, 'Dynamax Crystal');
insert into items values (1456, 'Dynamax Crystal');
insert into items values (1457, 'Dynamax Crystal');
insert into items values (1458, 'Dynamax Crystal');
insert into items values (1459, 'Dynamax Crystal');
insert into items values (1460, 'Dynamax Crystal');
insert into items values (1461, 'Dynamax Crystal');
insert into items values (1462, 'Dynamax Crystal');
insert into items values (1463, 'Dynamax Crystal');
insert into items values (1464, 'Dynamax Crystal');
insert into items values (1465, 'Dynamax Crystal');
insert into items values (1466, 'Dynamax Crystal');
insert into items values (1467, 'Dynamax Crystal');
insert into items values (1468, 'Dynamax Crystal');
insert into items values (1469, 'Dynamax Crystal');
insert into items values (1470, 'Dynamax Crystal');
insert into items values (1471, 'Dynamax Crystal');
insert into items values (1472, 'Dynamax Crystal');
insert into items values (1473, 'Dynamax Crystal');
insert into items values (1474, 'Dynamax Crystal');
insert into items values (1475, 'Dynamax Crystal');
insert into items values (1476, 'Dynamax Crystal');
insert into items values (1477, 'Dynamax Crystal');
insert into items values (1478, 'Dynamax Crystal');
insert into items values (1479, 'Dynamax Crystal');
insert into items values (1480, 'Dynamax Crystal');
insert into items values (1481, 'Dynamax Crystal');
insert into items values (1482, 'Dynamax Crystal');
insert into items values (1483, 'Dynamax Crystal');
insert into items values (1484, 'Dynamax Crystal');
insert into items values (1485, 'Dynamax Crystal');
insert into items values (1486, 'Dynamax Crystal');
insert into items values (1487, 'Dynamax Crystal');
insert into items values (1488, 'Dynamax Crystal');
insert into items values (1489, 'Dynamax Crystal');
insert into items values (1490, 'Dynamax Crystal');
insert into items values (1491, 'Dynamax Crystal');
insert into items values (1492, 'Dynamax Crystal');
insert into items values (1493, 'Dynamax Crystal');
insert into items values (1494, 'Dynamax Crystal');
insert into items values (1495, 'Dynamax Crystal');
insert into items values (1496, 'Dynamax Crystal');
insert into items values (1497, 'Dynamax Crystal');
insert into items values (1498, 'Dynamax Crystal');
insert into items values (1499, 'Dynamax Crystal');
insert into items values (1500, 'Dynamax Crystal');
insert into items values (1501, 'Dynamax Crystal');
insert into items values (1502, 'Dynamax Crystal');
insert into items values (1503, 'Dynamax Crystal');
insert into items values (1504, 'Dynamax Crystal');
insert into items values (1505, 'Dynamax Crystal');
insert into items values (1506, 'Dynamax Crystal');
insert into items values (1507, 'Dynamax Crystal');
insert into items values (1508, 'Dynamax Crystal');
insert into items values (1509, 'Dynamax Crystal');
insert into items values (1510, 'Dynamax Crystal');
insert into items values (1511, 'Dynamax Crystal');
insert into items values (1512, 'Dynamax Crystal');
insert into items values (1513, 'Dynamax Crystal');
insert into items values (1514, 'Dynamax Crystal');
insert into items values (1515, 'Dynamax Crystal');
insert into items values (1516, 'Dynamax Crystal');
insert into items values (1517, 'Dynamax Crystal');
insert into items values (1518, 'Dynamax Crystal');
insert into items values (1519, 'Dynamax Crystal');
insert into items values (1520, 'Dynamax Crystal');
insert into items values (1521, 'Dynamax Crystal');
insert into items values (1522, 'Dynamax Crystal');
insert into items values (1523, 'Dynamax Crystal');
insert into items values (1524, 'Dynamax Crystal');
insert into items values (1525, 'Dynamax Crystal');
insert into items values (1526, 'Dynamax Crystal');
insert into items values (1527, 'Dynamax Crystal');
insert into items values (1528, 'Dynamax Crystal');
insert into items values (1529, 'Dynamax Crystal');
insert into items values (1530, 'Dynamax Crystal');
insert into items values (1531, 'Dynamax Crystal');
insert into items values (1532, 'Dynamax Crystal');
insert into items values (1533, 'Dynamax Crystal');
insert into items values (1534, 'Dynamax Crystal');
insert into items values (1535, 'Dynamax Crystal');
insert into items values (1536, 'Dynamax Crystal');
insert into items values (1537, 'Dynamax Crystal');
insert into items values (1538, 'Dynamax Crystal');
insert into items values (1539, 'Dynamax Crystal');
insert into items values (1540, 'Dynamax Crystal');
insert into items values (1541, 'Dynamax Crystal');
insert into items values (1542, 'Dynamax Crystal');
insert into items values (1543, 'Dynamax Crystal');
insert into items values (1544, 'Dynamax Crystal');
insert into items values (1545, 'Dynamax Crystal');
insert into items values (1546, 'Dynamax Crystal');
insert into items values (1547, 'Dynamax Crystal');
insert into items values (1548, 'Dynamax Crystal');
insert into items values (1549, 'Dynamax Crystal');
insert into items values (1550, 'Dynamax Crystal');
insert into items values (1551, 'Dynamax Crystal');
insert into items values (1552, 'Dynamax Crystal');
insert into items values (1553, 'Dynamax Crystal');
insert into items values (1554, 'Dynamax Crystal');
insert into items values (1555, 'Dynamax Crystal');
insert into items values (1556, 'Dynamax Crystal');
insert into items values (1557, 'Dynamax Crystal');
insert into items values (1558, 'Dynamax Crystal');
insert into items values (1559, 'Dynamax Crystal');
insert into items values (1560, 'Dynamax Crystal');
insert into items values (1561, 'Dynamax Crystal');
insert into items values (1562, 'Dynamax Crystal');
insert into items values (1563, 'Dynamax Crystal');
insert into items values (1564, 'Dynamax Crystal');
insert into items values (1565, 'Dynamax Crystal');
insert into items values (1566, 'Dynamax Crystal');
insert into items values (1567, 'Dynamax Crystal');
insert into items values (1568, 'Dynamax Crystal');
insert into items values (1569, 'Dynamax Crystal');
insert into items values (1570, 'Dynamax Crystal');
insert into items values (1571, 'Dynamax Crystal');
insert into items values (1572, 'Dynamax Crystal');
insert into items values (1573, 'Dynamax Crystal');
insert into items values (1574, 'Dynamax Crystal');
insert into items values (1575, 'Dynamax Crystal');
insert into items values (1576, 'Dynamax Crystal');
insert into items values (1577, 'Dynamax Crystal');
insert into items values (1578, 'Dynamax Crystal');
